import type { Integration } from '../data/component-definitions'
import type { AutoGeneratedFieldExpression, FieldExpressionRead, FieldExpressionUpdate } from '@/types/fieldExpressions'

export interface PortConfiguration {
  id?: string
  component_instance_id: string
  parameter_id: string | null
  input_port_instance_id?: string | null
  setup_mode: 'user_set' | 'ai_filled' | 'deactivated'
  field_expression_id?: string | null
  expression_json?: any | null
  ai_name_override?: string | null
  ai_description_override?: string | null
  is_required_override?: boolean | null
  custom_port_name?: string | null
  custom_port_description?: string | null
  custom_parameter_type?: string | null
  custom_ui_component_properties?: any | null
  json_schema_override?: Record<string, any> | null
}

export interface ApiEdge {
  id: string
  origin: string
  destination: string
  origin_port?: string
  destination_port?: string
  order?: number | null
  parameter_name?: string
}

export interface ApiComponentInstance {
  id: string
  ref: string
  name: string
  component_id: string
  component_version_id: string
  tool_description?: {
    name: string
    description: string
    tool_properties?: Record<string, any>
    required_tool_properties?: string[]
  }
  parameters: Array<{
    name: string
    value: any
    display_order?: number | null
    type?: string
    nullable?: boolean
    default?: any | null
    ui_component?: string | null
    ui_component_properties?: any | null
    is_advanced?: boolean
    kind?: 'parameter' | 'input'
    is_tool_input?: boolean
    parameter_group_id?: string | null
    parameter_order_within_group?: number | null
    parameter_group_name?: string | null
  }>
  inputs?: any[]
  outputs?: any[]
  can_use_function_calling?: boolean
  function_callable?: boolean
  tools?: any[]
  subcomponents_info?: Array<{
    component_version_id: string
    parameter_name: string
    is_optional: boolean
  }>
  is_agent?: boolean
  is_start_node?: boolean
  component_name?: string
  component_description?: string
  tool_parameter_name?: string | null
  position?: { x: number; y: number } | null
  icon?: string | null
  integration?: Integration
  field_expressions?: FieldExpressionUpdate[] | FieldExpressionRead[]
  port_configurations?: PortConfiguration[]
}

export interface ApiRelationship {
  parent_component_instance_id: string
  child_component_instance_id: string
  parameter_name?: string
  order?: number | null
}

export interface GraphData {
  component_instances: ApiComponentInstance[]
  edges: ApiEdge[]
  relationships: ApiRelationship[]
  playground_input_schema?: Record<string, any>
  playground_field_types?: Record<string, 'messages' | 'json' | 'simple'>
}

export interface GraphUpdateResponse {
  graph_id?: string
  last_edited_time?: string | null
  last_edited_user_id?: string | null
  playground_input_schema?: Record<string, any>
  playground_field_types?: Record<string, 'messages' | 'json' | 'simple'>
  auto_generated_field_expressions?: AutoGeneratedFieldExpression[]
}

// ─── Graph API V2 payload types ─────────────────────────────────────

export interface ComponentParameterV2Payload {
  name: string
  value: any
  order: number | null
  type: string
  nullable: boolean
  default: any
  ui_component: string | null
  ui_component_properties: any | null
  is_advanced: boolean
  kind: 'parameter' | 'input'
  is_tool_input: boolean
  field_expression?: { expression_json: any } | null
  parameter_group_id?: string | null
  parameter_order_within_group?: number | null
  parameter_group_name?: string | null
}

export interface InputPortInstanceV2 {
  name: string
  field_expression: { expression_json: any }
}

// ─── Graph API V2 types ──────────────────────────────────────────────

export interface GraphMapNodeRef {
  id?: string
  file_key?: string
}

export interface GraphV2Node {
  instance_id?: string
  file_key?: string
  label?: string
  is_start_node?: boolean
}

export interface GraphV2Edge {
  id?: string
  from: GraphMapNodeRef
  to: GraphMapNodeRef
  order?: number | null
}

export interface GraphV2Relationship {
  parent: GraphMapNodeRef
  child: GraphMapNodeRef
  parameter_name: string
  order?: number | null
}

export interface GraphMapV2 {
  nodes: GraphV2Node[]
  edges: GraphV2Edge[]
  relationships: GraphV2Relationship[]
}

export interface GraphV2Response {
  graph_map: GraphMapV2
  tag_name?: string | null
  change_log?: string | null
  last_edited_time?: string | null
  last_edited_user_id?: string | null
}

export interface TopologyUpdateV2Data {
  nodes: Array<{ instance_id: string; label?: string | null; is_start_node?: boolean }>
  edges: GraphV2Edge[]
  relationships: GraphV2Relationship[]
  last_edited_time?: string | null
}

export interface ComponentCreateV2Data {
  component_id: string
  component_version_id: string
  label: string
  is_start_node?: boolean
  parameters: ComponentParameterV2Payload[]
  input_port_instances: InputPortInstanceV2[]
  port_configurations?: PortConfiguration[] | null
  integration?: Integration | null
  tool_description_override?: string | null
}

export interface ComponentUpdateV2Data {
  parameters: ComponentParameterV2Payload[]
  input_port_instances: InputPortInstanceV2[]
  port_configurations?: PortConfiguration[] | null
  integration?: Integration | null
  tool_description_override?: string | null
  label?: string | null
  is_start_node?: boolean | null
}

export interface ComponentV2Response {
  instance_id: string
  label?: string | null
  is_start_node?: boolean
  last_edited_time?: string | null
  last_edited_user_id?: string | null
}

export interface ComponentGetV2Response {
  component_instance: ApiComponentInstance
}
