"""add new column project_id

Revision ID: 40f09397fc95
Revises: c22a1d518176
Create Date: 2025-09-24 12:03:37.087001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40f09397fc95"
down_revision: Union[str, None] = "c22a1d518176"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spans", sa.Column("project_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_spans_project_id"), "spans", ["project_id"], unique=False)

    # Data migration: Copy project_id from attributes JSON to new column
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        UPDATE spans
        SET project_id = (attributes::jsonb->>'project_id')
        WHERE attributes::jsonb ? 'project_id'
        AND (attributes::jsonb->>'project_id') IS NOT NULL
        AND (attributes::jsonb->>'project_id') != ''
    """
        )
    )

    # Optional: Remove project_id from attributes JSON to clean up
    connection.execute(
        sa.text(
            """
        UPDATE spans
        SET attributes = (attributes::jsonb - 'project_id')::text
        WHERE attributes::jsonb ? 'project_id'
    """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Data migration rollback: Copy project_id back to attributes JSON
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        UPDATE spans
        SET attributes = jsonb_set(
            attributes::jsonb,
            '{project_id}',
            to_jsonb(project_id)
        )::text
        WHERE project_id IS NOT NULL
    """
        )
    )

    op.drop_index(op.f("ix_spans_project_id"), table_name="spans")
    op.drop_column("spans", "project_id")
    # ### end Alembic commands ###
