"""add graph_runner_id, tag_name

Revision ID: 55bf7791d9dd
Revises: 7a9e2b3f4c5d
Create Date: 2025-10-10 10:08:13.508158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bf7791d9dd'
down_revision: Union[str, None] = '7a9e2b3f4c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spans', sa.Column('graph_runner_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_spans_call_type'), table_name='spans')
    op.drop_index(op.f('ix_spans_environment'), table_name='spans')
    op.create_index(op.f('ix_spans_graph_runner_id'), 'spans', ['graph_runner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spans_graph_runner_id'), table_name='spans')
    op.create_index(op.f('ix_spans_environment'), 'spans', ['environment'], unique=False)
    op.create_index(op.f('ix_spans_call_type'), 'spans', ['call_type'], unique=False)
    op.drop_column('spans', 'graph_runner_id')
    # ### end Alembic commands ###
