"""add graph_runner_id, tag_name

Revision ID: 55bf7791d9dd
Revises: 7a9e2b3f4c5d
Create Date: 2025-10-10 10:08:13.508158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55bf7791d9dd"
down_revision: Union[str, None] = "7a9e2b3f4c5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spans", sa.Column("graph_runner_id", sa.UUID(), nullable=True))
    op.add_column("spans", sa.Column("tag_name", sa.String(), nullable=True))

    # Data migration: copy tag_version to tag_name, removing 'v' prefix
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE spans
            SET tag_name = CASE
                WHEN tag_version ~ '^[vV]'
                THEN SUBSTRING(tag_version FROM 2)
                ELSE tag_version
            END
            WHERE tag_version IS NOT NULL
            """
        )
    )

    op.drop_column("spans", "tag_version")
    op.drop_index(op.f("ix_spans_call_type"), table_name="spans")
    op.drop_index(op.f("ix_spans_environment"), table_name="spans")
    op.create_index(op.f("ix_spans_graph_runner_id"), "spans", ["graph_runner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spans_graph_runner_id"), table_name="spans")
    op.create_index(op.f("ix_spans_environment"), "spans", ["environment"], unique=False)
    op.create_index(op.f("ix_spans_call_type"), "spans", ["call_type"], unique=False)

    # Add tag_version column back
    op.add_column("spans", sa.Column("tag_version", sa.String(), nullable=True))

    # Data migration: copy tag_name back to tag_version, adding 'v' prefix
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE spans
            SET tag_version = 'v' || tag_name
            WHERE tag_name IS NOT NULL
            """
        )
    )

    op.drop_column("spans", "tag_name")
    op.drop_column("spans", "graph_runner_id")
    # ### end Alembic commands ###
