"""add llm token count columns

Revision ID: e8275ff746ca
Revises: 8b8e927371e4
Create Date: 2025-06-04 15:31:05.304865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8275ff746ca"
down_revision: Union[str, None] = "8b8e927371e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spans", sa.Column("llm_token_count_prompt", sa.Integer(), nullable=True))
    op.add_column("spans", sa.Column("llm_token_count_completion", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spans", "llm_token_count_completion")
    op.drop_column("spans", "llm_token_count_prompt")
    # ### end Alembic commands ###
