"""add-messages-table

Revision ID: f6dfd93b8baf
Revises: 48310acb4b96
Create Date: 2025-07-11 16:49:08.481287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dfd93b8baf'
down_revision: Union[str, None] = '48310acb4b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('span_id', sa.String(), nullable=False),
    sa.Column('input_content', sa.Text(), nullable=False),
    sa.Column('output_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
