from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator

from ada_backend.schemas.pipeline.base import ComponentInstanceSchema, ComponentRelationshipSchema
from ada_backend.schemas.pipeline.get_pipeline_schema import ComponentInstanceReadSchema


class PlaygroundFieldType(str, Enum):
    """Types for playground input field rendering."""

    MESSAGES = "messages"
    JSON = "json"
    SIMPLE = "simple"
    FILE = "file"


def _coerce_edge_endpoint(v):
    """Accept both a plain UUID and a dict like {"instance_id": "uuid", ...}."""
    if isinstance(v, dict):
        for key in ("instance_id", "id"):
            if key in v:
                return UUID(str(v[key])) if not isinstance(v[key], UUID) else v[key]
        raise ValueError(f"Edge endpoint dict must contain 'instance_id' or 'id', got keys: {list(v.keys())}")
    return v


class EdgeSchema(BaseModel):
    """Represents a graph edge between two nodes by their runnable ids"""

    id: UUID
    origin: UUID
    destination: UUID
    order: Optional[int] = None

    @field_validator("origin", "destination", mode="before")
    @classmethod
    def coerce_endpoint(cls, v):
        return _coerce_edge_endpoint(v)


class GraphGetResponse(BaseModel):
    """Complete pipeline definition"""

    component_instances: list[ComponentInstanceReadSchema]
    relationships: list[ComponentRelationshipSchema]
    edges: list[EdgeSchema]
    tag_name: Optional[str] = None
    change_log: Optional[str] = None
    last_edited_time: Optional[datetime] = None
    last_edited_user_id: Optional[UUID] = None
    playground_input_schema: Optional[dict] = None
    playground_field_types: Optional[dict[str, PlaygroundFieldType]] = None


class GraphLoadResponse(BaseModel):
    """Response model for loading a graph"""

    component_instances: list[ComponentInstanceReadSchema]
    relationships: list[ComponentRelationshipSchema]
    edges: list[EdgeSchema]


class GraphUpdateSchema(BaseModel):
    """Complete pipeline definition"""

    component_instances: list[ComponentInstanceSchema]
    relationships: list[ComponentRelationshipSchema]
    edges: list[EdgeSchema]

    # Optional optimistic locking: pass the last_edited_time from a previous update_graph
    # response. The backend returns 409 Conflict if the graph was modified since that timestamp.
    last_edited_time: Optional[datetime] = None


class AutoGeneratedFieldExpression(BaseModel):
    component_instance_id: UUID
    field_name: str
    expression_json: dict
    expression_text: Optional[str] = None


class GraphUpdateResponse(BaseModel):
    graph_id: UUID
    last_edited_time: Optional[datetime] = None
    last_edited_user_id: Optional[UUID] = None
    playground_input_schema: Optional[dict] = None
    playground_field_types: Optional[dict[str, PlaygroundFieldType]] = None
    auto_generated_field_expressions: list[AutoGeneratedFieldExpression] = Field(default_factory=list)


class ComponentNodeDTO(BaseModel):
    """DTO for component node"""

    id: UUID
    name: str
    is_start_node: bool
    is_trigger: bool = False
    component_instance_id: UUID | None = None
    graph_runner_id: UUID | None = None


class GraphDeployResponse(BaseModel):
    """
    Response returned after deploying a graph, indicating the current
    and previous graph versions bound to the project.
    """

    project_id: UUID
    draft_graph_runner_id: UUID
    prod_graph_runner_id: UUID
    previous_prod_graph_runner_id: Optional[UUID] = None


class GraphSaveVersionResponse(BaseModel):
    """
    Response returned after saving a version from a draft graph runner.
    """

    project_id: UUID
    saved_graph_runner_id: UUID
    tag_version: str
    draft_graph_runner_id: UUID


class ModificationHistoryItem(BaseModel):
    """Represents a single modification history entry"""

    time: datetime
    user_id: Optional[UUID] = None


class GraphModificationHistoryResponse(BaseModel):
    """Response model for graph modification history"""

    history: list[ModificationHistoryItem]
