import logging
from dataclasses import dataclass
from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy.orm import Session

from ada_backend.repositories.component_repository import (
    get_canonical_ports_for_component_versions,
    get_component_instance_by_id,
    get_component_instances_by_ids,
    get_component_parameter_definition_by_component_version,
    upsert_sub_component_input,
)
from ada_backend.repositories.edge_repository import delete_edge, get_edges, upsert_edge
from ada_backend.repositories.field_expression_repository import (
    create_field_expression,
    update_field_expression,
)
from ada_backend.repositories.graph_runner_repository import (
    get_component_nodes,
    get_latest_modification_history,
    graph_runner_exists,
    upsert_component_node,
)
from ada_backend.repositories.input_port_instance_repository import (
    create_input_port_instance,
    get_input_port_instances_for_component_instance,
    update_input_port_instance,
)
from ada_backend.repositories.port_definition_repository import (
    get_input_port_definition_id,
    get_output_port_definition_id,
)
from ada_backend.schemas.pipeline.graph_schema import (
    AutoGeneratedFieldExpression,
    GraphMapEdgeSchema,
    GraphMapNodeRefSchema,
    GraphMapRelationshipSchema,
    GraphTopologyNodeSchema,
)
from ada_backend.services.errors import GraphConflictError

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class _CanonicalExpression:
    target_instance_id: UUID
    field_name: str
    expression_json: dict


def check_optimistic_lock(session: Session, graph_runner_id: UUID, last_edited_time: datetime | None):
    if not last_edited_time:
        return
    latest_history = get_latest_modification_history(session, graph_runner_id)
    if latest_history and latest_history.created_at and latest_history.created_at > last_edited_time:
        raise GraphConflictError(graph_runner_id)


def sync_graph_topology(
    session: Session,
    graph_runner_id: UUID,
    nodes: list[GraphTopologyNodeSchema],
    edges: list[GraphMapEdgeSchema],
    relationships: list[GraphMapRelationshipSchema],
) -> list[AutoGeneratedFieldExpression]:
    existing_node_ids = {node.id for node in get_component_nodes(session, graph_runner_id)}
    payload_node_ids = {node.instance_id for node in nodes}
    missing = payload_node_ids - existing_node_ids
    if missing:
        raise ValueError(f"Nodes referenced in topology do not exist in graph: {missing}")

    for node in nodes:
        upsert_component_node(
            session,
            graph_runner_id=graph_runner_id,
            component_instance_id=node.instance_id,
            is_start_node=node.is_start_node,
        )

    previous_edge_ids = {edge.id for edge in get_edges(session, graph_runner_id)}
    new_edge_ids: set[UUID] = set()
    edge_pairs: list[tuple[UUID, UUID]] = []
    for edge in edges:
        origin = _resolve_edge_ref(edge.from_node, payload_node_ids)
        destination = _resolve_edge_ref(edge.to_node, payload_node_ids)

        if graph_runner_exists(session, destination) or graph_runner_exists(session, origin):
            raise ValueError("Nested graphs are not supported")

        edge_id = edge.id or uuid4()
        new_edge_ids.add(edge_id)
        edge_pairs.append((origin, destination))
        upsert_edge(
            session,
            id=edge_id,
            source_node_id=origin,
            target_node_id=destination,
            graph_runner_id=graph_runner_id,
            order=edge.order,
        )

    for edge_id in previous_edge_ids - new_edge_ids:
        delete_edge(session, edge_id)

    _sync_relationships(session, payload_node_ids, relationships)

    return _ensure_canonical_expressions_for_edges(session, edge_pairs)


def _resolve_edge_ref(ref: GraphMapNodeRefSchema, valid_ids: set[UUID]) -> UUID:
    if ref.id:
        if ref.id not in valid_ids:
            raise ValueError(f"Edge references unknown node id '{ref.id}'")
        return ref.id
    raise ValueError("Edge node references must use 'id' in topology save")


def _sync_relationships(
    session: Session,
    valid_ids: set[UUID],
    relationships: list[GraphMapRelationshipSchema],
) -> None:
    for relation in relationships:
        parent_id = _resolve_edge_ref(relation.parent, valid_ids)
        child_id = _resolve_edge_ref(relation.child, valid_ids)

        parent = get_component_instance_by_id(session, parent_id)
        if not parent:
            raise ValueError(f"Relationship parent component instance {parent_id} not found")

        param_defs = (
            get_component_parameter_definition_by_component_version(session, parent.component_version_id) or []
        )
        param_def = next((p for p in param_defs if p.name == relation.parameter_name), None)
        if not param_def:
            raise ValueError(
                f"Parameter '{relation.parameter_name}' not found in "
                f"component definitions for component version '{parent.component_version_id}'"
            )

        upsert_sub_component_input(
            session=session,
            parent_component_instance_id=parent_id,
            child_component_instance_id=child_id,
            parameter_definition_id=param_def.id,
            order=relation.order,
        )


def _ensure_canonical_expressions_for_edges(
    session: Session,
    edge_pairs: list[tuple[UUID, UUID]],
) -> list[AutoGeneratedFieldExpression]:
    """Auto-generate canonical RefNode field expressions for newly wired edges.

    For each edge whose target canonical input port has no existing field
    expression in the DB, creates a RefNode expression pointing from the
    source's canonical output to the target's canonical input and persists it.
    """
    if not edge_pairs:
        return []

    all_instance_ids = list({iid for pair in edge_pairs for iid in pair})
    db_instances = get_component_instances_by_ids(session, all_instance_ids)
    instance_to_cv: dict[UUID, UUID] = {iid: inst.component_version_id for iid, inst in db_instances.items()}

    component_version_ids = list(set(instance_to_cv.values()))
    canonical_ports_by_cv = get_canonical_ports_for_component_versions(session, component_version_ids)

    existing_fe_targets: set[tuple[UUID, str]] = set()
    for instance_id in {t for _, t in edge_pairs}:
        for port in get_input_port_instances_for_component_instance(session, instance_id):
            if port.field_expression_id:
                existing_fe_targets.add((instance_id, port.name))

    generated: list[_CanonicalExpression] = []
    for source_id, target_id in edge_pairs:
        if source_id not in instance_to_cv or target_id not in instance_to_cv:
            continue

        source_cv = instance_to_cv[source_id]
        target_cv = instance_to_cv[target_id]

        source_ports = canonical_ports_by_cv.get(source_cv, {})
        target_ports = canonical_ports_by_cv.get(target_cv, {})
        source_port_name = source_ports.get("output") or "output"
        target_port_name = target_ports.get("input") or "input"

        source_port_def_id = get_output_port_definition_id(session, source_cv, source_port_name)
        target_port_def_id = get_input_port_definition_id(session, target_cv, target_port_name)
        if not source_port_def_id or not target_port_def_id:
            continue

        if (target_id, target_port_name) not in existing_fe_targets:
            expression_json = {"type": "ref", "instance": str(source_id), "port": source_port_name}
            generated.append(_CanonicalExpression(target_id, target_port_name, expression_json))

    result: list[AutoGeneratedFieldExpression] = []

    for expr_info in generated:
        target_id = expr_info.target_instance_id
        field_name = expr_info.field_name
        expression_json = expr_info.expression_json

        ports = get_input_port_instances_for_component_instance(session, target_id)
        existing_port = next((p for p in ports if p.name == field_name), None)

        if existing_port:
            if existing_port.field_expression_id:
                update_field_expression(session, existing_port.field_expression_id, expression_json)
            else:
                fe = create_field_expression(session, expression_json)
                update_input_port_instance(session, existing_port.id, field_expression_id=fe.id)
        else:
            fe = create_field_expression(session, expression_json)
            create_input_port_instance(
                session=session,
                component_instance_id=target_id,
                name=field_name,
                field_expression_id=fe.id,
            )

        try:
            from engine.field_expressions.parser import unparse_expression
            from engine.field_expressions.serializer import from_json as expr_from_json

            text = unparse_expression(expr_from_json(expression_json))
        except Exception:
            text = None

        result.append(
            AutoGeneratedFieldExpression(
                component_instance_id=target_id,
                field_name=field_name,
                expression_json=expression_json,
                expression_text=text,
            )
        )

    return result
