"""Initial PostgreSQL schema for evaluations

Revision ID: 7239d8f74054
Revises:
Create Date: 2025-07-18 16:45:36.235838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7239d8f74054"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable UUID extension if not already enabled
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table(
        "questions_answers",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("uuid_generate_v4()")),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("groundtruth", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_answers_id"), "questions_answers", ["id"], unique=False)
    op.create_index(
        op.f("ix_questions_answers_organization_id"), "questions_answers", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_questions_answers_project_id"), "questions_answers", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_questions_answers_project_id"), table_name="questions_answers")
    op.drop_index(op.f("ix_questions_answers_organization_id"), table_name="questions_answers")
    op.drop_index(op.f("ix_questions_answers_id"), table_name="questions_answers")
    op.drop_table("questions_answers")
    # ### end Alembic commands ###
