import asyncio
import base64
import json
import logging
import mimetypes
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Optional, Type

from openai.types.chat import ChatCompletionMessageToolCall
from openinference.semconv.trace import OpenInferenceSpanKindValues, SpanAttributes
from opentelemetry import trace as trace_api
from pydantic import BaseModel, Field

from ada_backend.database.models import UIComponent, UIComponentProperties
from engine.components.component import Component
from engine.components.generated_file_attachment import (
    ATTACH_GENERATED_FILES_TOOL_DESCRIPTION,
    ATTACH_GENERATED_FILES_TOOL_NAME,
    append_file_parts_to_latest_user_message,
    attach_generated_files_tool_output,
    build_generated_pdf_message_parts,
    extract_attached_generated_files_from_artifacts,
    extract_generated_files_from_artifacts,
    mask_file_data_for_trace,
)
from engine.components.history_message_handling import HistoryMessageHandler
from engine.components.rag.formatter import Formatter
from engine.components.rag.retriever import RETRIEVER_CITATION_INSTRUCTION, RETRIEVER_TOOL_DESCRIPTION
from engine.components.types import AgentPayload, ChatMessage, ComponentAttributes, SourcedResponse, ToolDescription
from engine.components.utils import extract_source_ranks, load_str_to_json, merge_constrained_output_to_root
from engine.components.utils_prompt import fill_prompt_template
from engine.graph_runner.runnable import Runnable
from engine.llm_services.llm_service import CompletionService
from engine.temps_folder_utils import get_output_dir
from engine.trace.serializer import serialize_to_json
from engine.trace.trace_manager import TraceManager

LOGGER = logging.getLogger(__name__)

DEFAULT_FALLBACK_REACT_ANSWER = "I couldn't find a solution to your problem."

OUTPUT_TOOL_NAME = "chat_formatting_output_tool"
OUTPUT_TOOL_DESCRIPTION = (
    "Default tool to be used by the agent to answer in a structured format if no other tool is called"
)
SYSTEM_PROMPT_DEFAULT = (
    "Act as a helpful assistant. "
    "You can use tools to answer questions,"
    " but you can also answer directly if you have enough information."
)


class AIAgentInputs(BaseModel):
    messages: Optional[list[ChatMessage]] = Field(
        default_factory=list,
        description="The history of messages in the conversation.",
    )
    input_filepaths: Optional[list[str]] = Field(
        default=None,
        description=(
            "Run-local file paths to attach directly to the LLM request. "
            "Use this to pass files generated by upstream components such as Python Code Runner."
        ),
    )
    initial_prompt: Optional[str] = Field(
        default=SYSTEM_PROMPT_DEFAULT,
        description=(
            "This prompt will be used to initialize the agent and set its behavior."
            " It can be used to provide context or instructions for the agent."
            " It will be used as the first message of the conversation in the agent's memory."
            " You can use it to set the agent's personality, role,"
            "or to provide specific instructions on how to handle certain types of questions."
            " The conversation you have with the agent (or your single message)"
            " is going to be added after this first message."
        ),
        json_schema_extra={
            "is_tool_input": False,
            "is_prompt": True,
            "ui_component": UIComponent.TEXTAREA,
            "ui_component_properties": UIComponentProperties(
                label="System Prompt",
            ).model_dump(exclude_unset=True, exclude_none=True),
        },
    )
    output_format: Optional[str | dict] = Field(
        default=None,
        description=(
            "JSON schema defining the properties/parameters of the output tool. "
            'Example: {"answer": {"type": "string", "description": "The answer content"}, '
            '"is_ending_conversation": {"type": "boolean", "description": "End conversation?"}}'
        ),
        json_schema_extra={
            "is_tool_input": False,
            "ui_component": UIComponent.TEXTAREA,
            "ui_component_properties": UIComponentProperties(
                label="Output Format",
            ).model_dump(exclude_unset=True, exclude_none=True),
            "is_advanced": True,
            "drives_output_schema": True,
        },
    )
    # Allow any other fields to be passed through
    model_config = {"extra": "allow"}


class AIAgentOutputs(BaseModel):
    output: str = Field(description="The string content of the final message from the agent.")
    full_message: ChatMessage = Field(description="The full final message object from the agent.")
    is_final: bool = Field(default=False, description="Indicates if this is the final output of the agent.")
    artifacts: dict[str, Any] = Field(default_factory=dict, description="Artifacts produced by the agent.")

    model_config = {"extra": "allow"}


def format_output_tool_description(
    tool_name: str,
    tool_description: str,
    tool_properties: dict,
    required_properties: Optional[list] = None,
) -> ToolDescription:
    """
    Format an output tool description for the React agent.

    Args:
        tool_name: Name of the output tool
        tool_description: Description of what the tool does
        tool_properties: JSON schema defining the tool's parameters
        required_properties: List of required property names. If None, all properties are required.

    Returns:
        ToolDescription for the output tool
    """
    if required_properties is None:
        required_properties = list(tool_properties.keys())

    return ToolDescription(
        name=tool_name,
        description=tool_description,
        tool_properties=tool_properties,
        required_tool_properties=required_properties,
    )


def get_default_output_tool_description() -> ToolDescription:
    """
    Get the default output tool description for conversation answers.

    Returns:
        Default ToolDescription for structured conversation responses
    """
    return format_output_tool_description(
        tool_name="conversation_answer",
        tool_description=(
            "Generate a structured answer for the conversation. Use this tool when you have "
            "gathered enough information to provide a comprehensive response to the user's question. "
            "This tool allows you to provide both the answer content and indicate whether the "
            "conversation should continue or end."
        ),
        tool_properties={
            "answer": {
                "type": "string",
                "description": "The answer or response content for the user's question or request.",
            },
            "is_ending_conversation": {
                "type": "boolean",
                "description": (
                    "Whether this response should end the conversation (true) or "
                    "allow for follow-up questions (false)."
                ),
            },
        },
        required_properties=["answer", "is_ending_conversation"],
    )


class AIAgent(Component):
    # TODO: It works as a migrated component, but it still uses legacy AgentPayload
    migrated = True

    @classmethod
    def get_canonical_ports(cls) -> dict[str, Optional[str]]:
        return {"input": "messages", "output": "output"}

    @classmethod
    def get_inputs_schema(cls) -> Type[BaseModel]:
        return AIAgentInputs

    @classmethod
    def get_outputs_schema(cls) -> Type[BaseModel]:
        return AIAgentOutputs

    def __init__(
        self,
        completion_service: CompletionService,
        trace_manager: TraceManager,
        tool_description: ToolDescription,
        component_attributes: ComponentAttributes,
        agent_tools: Optional[list[Runnable] | Runnable] = None,
        run_tools_in_parallel: bool = True,
        max_iterations: int = 3,
        max_tools_per_iteration: Optional[int] = 4,
        input_data_field_for_messages_history: str = "messages",
        first_history_messages: int = 1,
        last_history_messages: int = 50,
        allow_tool_shortcuts: bool = False,
        date_in_system_prompt: bool = False,
        tool_pre_configured_inputs: Optional[dict[str, dict[str, Any]]] = None,
        skip_tools_with_missing_oauth: bool = True,
        capability_resolver: Optional[Callable[[list[str]], set[str]]] = None,
    ) -> None:
        super().__init__(
            trace_manager=trace_manager,
            tool_description=tool_description,
            component_attributes=component_attributes,
        )
        self._skip_unavailable_tools = skip_tools_with_missing_oauth
        self.run_tools_in_parallel = run_tools_in_parallel
        if agent_tools is None:
            self.agent_tools = []
        else:
            self.agent_tools = agent_tools if isinstance(agent_tools, list) else [agent_tools]
        self._first_history_messages = first_history_messages
        self._last_history_messages = last_history_messages
        self._memory_handling = HistoryMessageHandler(self._first_history_messages, self._last_history_messages)
        self._max_iterations = max_iterations
        self._max_tools_per_iteration = max_tools_per_iteration
        self._current_iteration = 0
        self._completion_service = completion_service
        self.input_data_field_for_messages_history = input_data_field_for_messages_history
        self._allow_tool_shortcuts = allow_tool_shortcuts
        self._date_in_system_prompt = date_in_system_prompt
        self._capability_resolver = capability_resolver
        # Keyed by tool description name; values are pre-configured literal run inputs
        # that are merged with LLM-provided arguments in _run_tool_call (LLM args win).
        self._tool_pre_configured_inputs: dict[str, dict[str, Any]] = tool_pre_configured_inputs or {}
        self._tool_registry: dict[str, tuple[Runnable, ToolDescription, dict[str, Any]]] = {}

        # Tool cache is snapshotted at init; provide agent_tools up front.
        self._build_tool_cache()
        self._formatter = Formatter(add_sources=False, component_attributes=component_attributes)
        self._has_retriever_tool = self._check_for_retriever_tool()

    async def close(self) -> None:
        for tool in self.agent_tools:
            try:
                await tool.close()
            except Exception as e:
                LOGGER.error(f"Error closing tool: {e}", exc_info=True)

    @staticmethod
    def _get_output_tool_description(output_format: str | dict | None) -> Optional[ToolDescription]:
        """
        Get the output tool description using the same pattern as RAG.

        Returns:
            ToolDescription if all required output tool parameters are set, None otherwise.
        """
        # If no output tool is configured, return None
        if not any([output_format]):
            return None

        # Parse JSON strings to appropriate data types
        if isinstance(output_format, str):
            try:
                parsed_output_tool_properies = load_str_to_json(output_format)
            except ValueError as e:
                raise ValueError(f"Invalid 'output_format' parameter: {e}") from e
        else:
            parsed_output_tool_properies = output_format
        if parsed_output_tool_properies is None:
            return None

        required_properties = list[Any](parsed_output_tool_properies.keys())
        return ToolDescription(
            name=OUTPUT_TOOL_NAME,
            description=OUTPUT_TOOL_DESCRIPTION,
            tool_properties=parsed_output_tool_properies,
            required_tool_properties=required_properties,
        )

    def _build_tool_cache(self) -> None:
        """
        Expand tool descriptions for all agent tools.

        Calls get_tool_descriptions() on each tool to support:
        - Single-tool components (default): returns [self.tool_description]
        - Multi-tool components (e.g., RemoteMCPTool): returns multiple ToolDescriptions

        When skip_tools_with_missing_oauth is True, tools where is_available() returns
        False are silently excluded from the registry so the LLM never sees them.

        Caches a single mapping for both LLM listing and fast lookup.
        """
        self._tool_registry: dict[str, tuple[Runnable, ToolDescription, dict[str, Any]]] = {}

        for tool in self.agent_tools:
            if self._skip_unavailable_tools and not tool.is_available():
                LOGGER.warning(
                    "Skipping unavailable tool '%s': is_available() returned False.",
                    tool.component_attributes.component_instance_name,
                )
                continue

            descriptions = tool.get_tool_descriptions()
            # Normalize to list if single ToolDescription
            if not isinstance(descriptions, list):
                descriptions = [descriptions]

            for desc in descriptions:
                if desc.name in self._tool_registry:
                    LOGGER.warning(f"Duplicate tool name '{desc.name}' - overriding previous mapping")
                pre_configured = self._tool_pre_configured_inputs.get(desc.name, {})
                self._tool_registry[desc.name] = (tool, desc, pre_configured)

    def _check_for_retriever_tool(self) -> bool:
        return RETRIEVER_TOOL_DESCRIPTION.name in self._tool_registry

    def _get_tool_descriptions_for_llm(self, include_generated_file_tool: bool = False) -> list[ToolDescription]:
        """Return tool descriptions for LLM function calling."""
        tool_descriptions = [desc for _, desc, _ in self._tool_registry.values()]
        if include_generated_file_tool:
            tool_descriptions.append(ATTACH_GENERATED_FILES_TOOL_DESCRIPTION)
        return tool_descriptions

    @staticmethod
    def _resolve_run_file_path(input_filepath: str) -> tuple[Path, str]:
        output_dir = get_output_dir().resolve()
        requested_path = Path(input_filepath)
        if requested_path.is_absolute():
            raise ValueError(f"Input file path must be relative to the run output directory: {input_filepath}")

        resolved_path = (output_dir / requested_path).resolve()
        if not resolved_path.is_relative_to(output_dir):
            raise ValueError(f"Input file path escapes the run output directory: {input_filepath}")
        if not resolved_path.is_file():
            raise ValueError(f"Input file not found in run output directory: {input_filepath}")
        return resolved_path, resolved_path.relative_to(output_dir).as_posix()

    @classmethod
    def _build_file_content_parts(cls, input_filepaths: list[str]) -> list[dict[str, Any]]:
        file_content_parts = []
        for input_filepath in input_filepaths:
            file_path, filename = cls._resolve_run_file_path(input_filepath)
            media_type = mimetypes.guess_type(file_path.name)[0] or "application/octet-stream"
            encoded_file = base64.b64encode(file_path.read_bytes()).decode("utf-8")
            file_content_parts.append({
                "type": "file",
                "file": {
                    "filename": filename,
                    "file_data": f"data:{media_type};base64,{encoded_file}",
                },
            })
        return file_content_parts

    def _ensure_file_capability(self, input_filepaths: Optional[list[str]]) -> None:
        if not input_filepaths:
            return

        provider = getattr(self._completion_service, "_provider", None)
        model_name = getattr(self._completion_service, "_model_name", None)
        model_reference = f"{provider}:{model_name}" if provider and model_name else None
        supported_references = self._resolve_capabilities(["file"])
        if model_reference not in supported_references:
            raise ValueError(f"File content is not supported for model '{model_reference or model_name}'.")

    def _resolve_capabilities(self, capabilities: list[str]) -> set[str]:
        if self._capability_resolver is None:
            return set()
        return self._capability_resolver(capabilities)

    @staticmethod
    def _extract_filenames_from_content(content: str | list | None) -> set[str]:
        if not isinstance(content, list):
            return set()

        filenames = set()
        for item in content:
            if not isinstance(item, dict):
                continue
            file_payload = item.get("file")
            if isinstance(file_payload, dict) and isinstance(file_payload.get("filename"), str):
                filenames.add(file_payload["filename"])
        return filenames

    def _attach_input_files_to_latest_user_message(
        self,
        agent_input: AgentPayload,
        input_filepaths: Optional[list[str]],
    ) -> None:
        if not input_filepaths:
            return

        file_content_parts = self._build_file_content_parts(input_filepaths)
        for message in reversed(agent_input.messages):
            if message.role != "user":
                continue

            existing_filenames = self._extract_filenames_from_content(message.content)
            new_file_parts = [
                part for part in file_content_parts if part["file"]["filename"] not in existing_filenames
            ]
            if not new_file_parts:
                return

            if isinstance(message.content, list):
                message.content = [*message.content, *new_file_parts]
            else:
                message.content = [
                    {
                        "type": "text",
                        "text": message.content or "",
                    },
                    *new_file_parts,
                ]
            return

        agent_input.messages.append(ChatMessage(role="user", content=file_content_parts))

    @staticmethod
    def _extract_file_metadata(ctx: Optional[dict]) -> list[dict[str, str]]:
        if not ctx:
            return []

        files_info = []
        for key, value in ctx.items():
            if isinstance(value, dict) and value.get("type") == "file":
                filename = value.get("filename", "")
                if filename:
                    files_info.append({
                        "key": key,
                        "filename": filename,
                    })
        return files_info

    # --- ORIGINAL CORE LOGIC (unchanged) ---
    async def _run_tool_call(
        self,
        *original_agent_inputs: AgentPayload,
        tool_call: ChatCompletionMessageToolCall,
        ctx: Optional[dict] = None,
    ) -> tuple[str, AgentPayload]:
        tool_call_id = tool_call.id
        tool_function_name = tool_call.function.name
        tool_arguments = json.loads(tool_call.function.arguments)
        LOGGER.info(
            f"Tool call: {tool_function_name} (id={tool_call_id}) with argument keys={list(tool_arguments.keys())}"
        )

        if tool_function_name == ATTACH_GENERATED_FILES_TOOL_NAME:
            return tool_call_id, attach_generated_files_tool_output(
                original_agent_inputs,
                tool_arguments.get("filenames"),
            )

        tool_entry = self._tool_registry.get(tool_function_name)
        if tool_entry is None:
            raise ValueError(f"Tool {tool_function_name} not found in agent_tools.")
        tool_to_use, _, pre_configured = tool_entry
        # TODO: replace this flag-based wiring with a proper function-calling→input translation hook
        if getattr(tool_to_use, "requires_tool_name", False):
            tool_arguments["tool_name"] = tool_function_name
        # Merge pre-configured literal inputs with LLM-provided arguments; LLM args win.
        merged_arguments = {**pre_configured, **tool_arguments}
        try:
            LOGGER.debug(f"Calling tool {tool_function_name} with argument keys={list(merged_arguments.keys())}")
            tool_output = await tool_to_use.run(ctx=ctx, **merged_arguments)
        except Exception as e:
            LOGGER.error(f"Error running tool {tool_function_name}: {type(e).__name__}", exc_info=True)
            tool_output = AgentPayload(messages=[ChatMessage(role="assistant", content=str(e))], error=str(e))
        return tool_call_id, tool_output

    async def _process_tool_calls(
        self, *original_agent_inputs: AgentPayload, tool_calls: list[dict], ctx: Optional[dict] = None
    ) -> tuple[dict[str, AgentPayload], list[dict]]:
        tool_outputs: dict[str, AgentPayload] = {}

        # Determine max tools to execute
        max_tools = len(tool_calls)
        if self._max_tools_per_iteration is not None:
            max_tools = min(max_tools, self._max_tools_per_iteration)

        if len(tool_calls) > max_tools:
            LOGGER.warning(f"Limiting tool calls from {len(tool_calls)} to {max_tools} per iteration")

        # Get the subset of tool calls we'll actually process
        tools_to_process = tool_calls[:max_tools]

        if self.run_tools_in_parallel:
            tasks = [
                self._run_tool_call(
                    *original_agent_inputs,
                    tool_call=tool_call,
                    ctx=ctx,
                )
                for tool_call in tools_to_process
            ]
            results = await asyncio.gather(*tasks)
            for tool_id, agent_output in results:
                tool_outputs[tool_id] = agent_output
        else:
            # Process sequentially
            for tool_call in tools_to_process:
                tool_call_id, tool_output = await self._run_tool_call(
                    *original_agent_inputs,
                    tool_call=tool_call,
                    ctx=ctx,
                )
                tool_outputs[tool_call_id] = tool_output
        return tool_outputs, tools_to_process

    async def _run_core(
        self,
        *inputs: AgentPayload | dict,
        ctx: Optional[dict] = None,
        initial_prompt: str,
        output_tool_description: ToolDescription | None,
        inputs_dict: Optional[dict] = None,
        **kwargs,
    ) -> AgentPayload:
        # Exact previous logic
        original_agent_input = inputs[0]
        if not isinstance(original_agent_input, AgentPayload):
            # Accept BaseModel-like inputs (e.g., NodeData) defensively
            if hasattr(original_agent_input, "model_dump") and callable(original_agent_input.model_dump):
                original_agent_input = original_agent_input.model_dump(exclude_none=True)
            # Ensure messages field populated from configured input key
            original_agent_input["messages"] = original_agent_input[self.input_data_field_for_messages_history]
            original_agent_input = AgentPayload(**original_agent_input)
        system_message = next((msg for msg in original_agent_input.messages if msg.role == "system"), None)

        # Prepare system prompt content
        system_prompt_content = initial_prompt

        # TODO: Refactor logic. AI Agent is coupled to Retriever tool here. Tools should inject their own instructions
        # without AI Agent knowing the specifics
        if self._has_retriever_tool:
            system_prompt_content = f"{initial_prompt}\n{RETRIEVER_CITATION_INSTRUCTION}"

        if self._date_in_system_prompt:
            # TODO: add the timezone of the user
            current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            system_prompt_content = f"Current date and time: {current_date}\n\n{system_prompt_content}"

        files_metadata = self._extract_file_metadata(ctx)
        if files_metadata:
            file_list = "\n".join([f"- {f['filename']}" for f in files_metadata])
            files_instruction = (
                "\n\nAvailable input files:\n"
                f"{file_list}\n\n"
                "You can reference these files directly by filename in your Python code "
                "(using the input_filepaths parameter)."
            )
            system_prompt_content += files_instruction

        generated_files = extract_generated_files_from_artifacts(original_agent_input.artifacts)
        if generated_files:
            generated_file_list = "\n".join([f"- {filename}" for filename in generated_files])
            generated_files_instruction = (
                "\n\nAvailable generated files:\n"
                f"{generated_file_list}\n\n"
                "You can reference these files by filename in Python Code Runner calls using input_filepaths. "
                "For generated PDF files that you need to read directly, call "
                f"{ATTACH_GENERATED_FILES_TOOL_NAME} with the exact filenames first."
            )
            system_prompt_content += generated_files_instruction

        inputs_dict = inputs_dict or {}
        if kwargs:
            inputs_dict = {**inputs_dict, **kwargs}
        input_filepaths = inputs_dict.get("input_filepaths")
        self._ensure_file_capability(input_filepaths)

        merged_dict = {**(ctx or {}), **inputs_dict}

        filled_system_prompt = fill_prompt_template(
            prompt_template=system_prompt_content,
            component_name=self.component_attributes.component_instance_name,
            variables=merged_dict,
        )
        masked_system_prompt = fill_prompt_template(
            prompt_template=system_prompt_content,
            component_name=self.component_attributes.component_instance_name,
            variables=merged_dict,
            reveal_secrets=False,
        )

        if system_message is None:
            original_agent_input.messages.insert(
                0,
                ChatMessage(
                    role="system",
                    content=filled_system_prompt,
                ),
            )
        else:
            # Some React derived agents are tools of React agents, hence we need
            # to replace the system message by the initial prompt
            original_agent_input.messages[0] = ChatMessage(
                role="system",
                content=filled_system_prompt,
            )
        attached_files = extract_attached_generated_files_from_artifacts(original_agent_input.artifacts)
        original_agent_input.artifacts.pop("attached_files", None)

        agent_input = original_agent_input.model_copy(deep=True)
        self._attach_input_files_to_latest_user_message(agent_input, input_filepaths)
        history_messages_handled = self._memory_handling.get_truncated_messages_history(agent_input.messages)
        tool_choice = "auto" if self._current_iteration + 1 < self._max_iterations else "none"
        with self.trace_manager.start_span("Agentic reflexion") as span:
            llm_input_messages = [msg.model_dump() for msg in history_messages_handled]
            generated_pdf_parts = build_generated_pdf_message_parts(attached_files)
            append_file_parts_to_latest_user_message(llm_input_messages, generated_pdf_parts)
            trace_input_messages = mask_file_data_for_trace(llm_input_messages)
            for message in trace_input_messages:
                if message.get("role") == "system":
                    message["content"] = masked_system_prompt
                    break
            # TODO(security): user/tool/assistant history messages can still contain plaintext
            # secrets coming from upstream concat/unwrap. serialize_to_json masks SecretStr only;
            # per-role redaction requires catalog-level "sensitive port" metadata.
            span.set_attributes({
                SpanAttributes.OPENINFERENCE_SPAN_KIND: OpenInferenceSpanKindValues.LLM.value,
                SpanAttributes.LLM_INPUT_MESSAGES: serialize_to_json(trace_input_messages, shorten_string=True),
                SpanAttributes.LLM_MODEL_NAME: self._completion_service._model_name,
                "model_id": (
                    str(self._completion_service._model_id) if self._completion_service._model_id is not None else None
                ),
            })
            chat_response = await self._completion_service.function_call_async(
                messages=llm_input_messages,
                tools=self._get_tool_descriptions_for_llm(include_generated_file_tool=bool(generated_files)),
                tool_choice=tool_choice,
                structured_output_tool=output_tool_description,
            )

            span.set_attributes({
                SpanAttributes.LLM_OUTPUT_MESSAGES: serialize_to_json(chat_response.choices[0].message.model_dump()),
            })
            span.set_status(trace_api.StatusCode.OK)

            all_tool_calls = chat_response.choices[0].message.tool_calls

            if not all_tool_calls:
                self.log_trace_event("No tool calls found in the response. Returning the chat response.")
                imgs = get_images_from_message(history_messages_handled)

                artifacts = (
                    dict(agent_input.artifacts) if hasattr(agent_input, "artifacts") and agent_input.artifacts else {}
                )

                response_content = chat_response.choices[0].message.content or ""
                # TODO Make sources a first-class typed output (instead of going through artifacts)
                if "sources" in artifacts and artifacts["sources"]:
                    sourced_response = SourcedResponse(
                        response=response_content,
                        sources=artifacts["sources"],
                        is_successful=True,
                    )
                    filtered_response = self._formatter._renumber_sources(sourced_response)
                    artifacts["sources"] = filtered_response.sources
                    response_content = filtered_response.response

                    if filtered_response.sources:
                        original_retrieval_ranks, original_reranker_ranks, total_retrieved, total_reranked = (
                            extract_source_ranks(filtered_response.sources)
                        )
                        trace_attrs = {
                            "original_retrieval_rank": json.dumps(original_retrieval_ranks),
                            "original_reranker_rank": json.dumps(original_reranker_ranks),
                        }
                        if total_retrieved is not None:
                            trace_attrs["total_retrieved_chunks"] = total_retrieved
                        if total_reranked is not None:
                            trace_attrs["total_reranked_chunks"] = total_reranked
                        span.set_attributes(trace_attrs)

                if imgs:
                    artifacts["images"] = imgs
                else:
                    LOGGER.debug("No images found in the response.")
                return AgentPayload(
                    messages=[ChatMessage(role="assistant", content=response_content)],
                    is_final=True,
                    artifacts=artifacts,
                )

        agent_outputs, processed_tool_calls = await self._process_tool_calls(
            original_agent_input,
            tool_calls=all_tool_calls,
            ctx=ctx,
        )

        collected_artifacts = _collect_output_artifacts(agent_outputs)

        agent_input.messages.append(
            ChatMessage(
                role="assistant",
                content=None,
                tool_calls=processed_tool_calls,
            )
        )
        for tool_call_id, agent_output in agent_outputs.items():
            agent_input.messages.append(
                ChatMessage(
                    role="tool",
                    content=agent_output.messages[0].content if agent_output.messages else None,
                    tool_call_id=tool_call_id,
                )
            )

        agent_input.artifacts.update(collected_artifacts)

        # If there's 0 or more than 1 final outputs, run the agent again
        successful_output_count = sum(agent_output.is_final for agent_output in agent_outputs.values())
        if successful_output_count == 1 and self._allow_tool_shortcuts:
            self.log_trace_event(
                message=(
                    f"Found a unique successful output after {self._current_iteration + 1} "
                    f"iterations. Returning the final output."
                )
            )
            final_output: AgentPayload = next(
                agent_output for agent_output in agent_outputs.values() if agent_output.is_final
            )

            if collected_artifacts:
                final_output.artifacts.update(collected_artifacts)
            return final_output

        elif self._current_iteration + 1 < self._max_iterations:
            self.log_trace_event(
                message=(f"Number of successful tool outputs: {successful_output_count}. Running the agent again.")
            )
            self._current_iteration += 1
            return await self._run_core(
                agent_input,
                ctx=ctx,
                initial_prompt=initial_prompt,
                output_tool_description=output_tool_description,
                inputs_dict=inputs_dict,
                **kwargs,
            )
        else:
            LOGGER.error(
                f"Reached the maximum number of iterations ({self._max_iterations}) and still asks for tools."
                " This should not happen."
            )

            return AgentPayload(
                messages=[ChatMessage(role="assistant", content=DEFAULT_FALLBACK_REACT_ANSWER)],
                is_final=False,
            )

    # --- Thin adapter to typed I/O ---
    async def _run_without_io_trace(self, inputs: AIAgentInputs, ctx: dict) -> AIAgentOutputs:
        # Map typed inputs to the original call style
        initial_prompt = inputs.initial_prompt
        output_format = inputs.output_format
        output_tool_description = self._get_output_tool_description(output_format)

        payload_dict = inputs.model_dump(exclude_none=True)
        agent_payload = AgentPayload(**payload_dict) if "messages" in payload_dict else payload_dict

        # Extract inputs_dict from original ReActAgentInputs for template variable filling
        # Exclude messages and AgentPayload-specific fields (error, artifacts, is_final)
        inputs_dict_for_template = {
            k: v for k, v in payload_dict.items() if k not in ["messages", "error", "artifacts", "is_final"]
        }

        core_result = await self._run_core(
            agent_payload,
            ctx=ctx,
            initial_prompt=initial_prompt,
            output_tool_description=output_tool_description,
            inputs_dict=inputs_dict_for_template,
        )

        # Map original output back to typed outputs
        final_message = (
            core_result.messages[-1] if core_result.messages else ChatMessage(role="assistant", content=None)
        )
        outputs = AIAgentOutputs(
            output=final_message.content or "",
            full_message=final_message,
            is_final=core_result.is_final,
            artifacts=core_result.artifacts or {},
        )

        merge_constrained_output_to_root(outputs, final_message.content, output_format)

        return outputs


def get_dummy_ai_agent_description() -> ToolDescription:
    return ToolDescription(
        name="exemple_base_ai_agent",
        description="",
        tool_properties={},
        required_tool_properties=[],
    )


def get_images_from_message(messages: list[ChatMessage]) -> list[str]:
    if messages:
        message = messages[-1]
        if message.content and "}" in message.content:
            try:
                json_content = json.loads(message.content)
                if "artifacts" in json_content and "images" in json_content["artifacts"]:
                    imgs = json_content["artifacts"]["images"]
                else:
                    imgs = []
            except (
                json.JSONDecodeError,
                TypeError,
            ):
                LOGGER.debug("Parsing the image response from JSON failed")
                imgs = []
            return imgs
    return []


def _collect_output_artifacts(agent_outputs: dict[str, AgentPayload]) -> dict[str, Any]:
    # TODO: Refactor to use typed approach instead of dict-based artifacts

    collected_artifacts = {}
    all_sources = []

    for tool_call_id, agent_output in agent_outputs.items():
        if agent_output.artifacts:
            if "sources" in agent_output.artifacts:
                sources = agent_output.artifacts["sources"]
                all_sources.extend(sources)

            for key, value in agent_output.artifacts.items():
                if key != "sources":
                    collected_artifacts[key] = value

    if all_sources:
        collected_artifacts["sources"] = all_sources

    return collected_artifacts
