global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: 'ada-backend'
   scrape_interval: 5s
   static_configs:
     - targets: ['host.docker.internal:8000']