global:
  scrape_interval: 10s

scrape_configs:
  # Prometheus scrapes its own metrics for internal monitoring
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  # Ada-backend metrics: HTTP performance + feature metrics
  - job_name: 'ada-backend'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9100']