global:
  scrape_interval: 10s

scrape_configs:
  # Prometheus scrapes its own metrics for internal monitoring
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  # Scrapes performance metrics from FastAPI app via OpenTelemetry
  # Connects to: ada_backend/instrumentation.py -> start_http_server(port=9464)
  - job_name: 'ada-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9464']  # Performance metrics endpoint