"""add trace query indexes

Revision ID: 19f9fe79128a
Revises: cc83bece26de
Create Date: 2026-03-17 11:04:53.671268

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19f9fe79128a"
down_revision: Union[str, None] = "cc83bece26de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_traces_span_messages_span_id"), "span_messages", ["span_id"], unique=False, schema="traces"
    )
    op.create_index(
        "ix_traces_spans_root_listing",
        "spans",
        ["project_id", "start_time"],
        unique=False,
        schema="traces",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_traces_spans_root_listing",
        table_name="spans",
        schema="traces",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.drop_index(op.f("ix_traces_span_messages_span_id"), table_name="span_messages", schema="traces")
    # ### end Alembic commands ###
