"""add tag to graph runner

Revision ID: 1eb7c34db2a7
Revises: 3253550650e4
Create Date: 2025-09-19 15:24:22.001246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1eb7c34db2a7"
down_revision: Union[str, None] = "c565c7904a64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graph_runners", sa.Column("tag_version", sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Initialize existing graph runners with v0.0.1 (only for production environment)
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
        UPDATE graph_runners
        SET tag_version = 'v0.0.1'
        WHERE tag_version IS NULL
        AND id IN (
            SELECT graph_runner_id
            FROM project_env_binding
            WHERE environment = 'production'
        )
    """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graph_runners", "tag_version")
    # ### end Alembic commands ###
