"""add json schema

Revision ID: 2326e3fdacaa
Revises: c2e594ae12bd
Create Date: 2025-10-16 18:47:42.083418

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2326e3fdacaa"
down_revision: Union[str, None] = "c2e594ae12bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
