"""fix cron polling index

Revision ID: 26682b086df6
Revises: c79f503f855e
Create Date: 2025-11-07 12:01:08.127466

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "26682b086df6"
down_revision: Union[str, None] = "c79f503f855e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_endpoint_polling_history_cron_id"), table_name="endpoint_polling_history", schema="scheduler"
    )
    op.drop_index(op.f("ix_endpoint_polling_history_id"), table_name="endpoint_polling_history", schema="scheduler")
    op.drop_index(
        op.f("ix_endpoint_polling_history_tracked_value"), table_name="endpoint_polling_history", schema="scheduler"
    )
    op.create_index(
        op.f("ix_scheduler_endpoint_polling_history_cron_id"),
        "endpoint_polling_history",
        ["cron_id"],
        unique=False,
        schema="scheduler",
    )
    op.create_index(
        op.f("ix_scheduler_endpoint_polling_history_id"),
        "endpoint_polling_history",
        ["id"],
        unique=False,
        schema="scheduler",
    )
    op.create_index(
        op.f("ix_scheduler_endpoint_polling_history_tracked_value"),
        "endpoint_polling_history",
        ["tracked_value"],
        unique=False,
        schema="scheduler",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_scheduler_endpoint_polling_history_tracked_value"),
        table_name="endpoint_polling_history",
        schema="scheduler",
    )
    op.drop_index(
        op.f("ix_scheduler_endpoint_polling_history_id"), table_name="endpoint_polling_history", schema="scheduler"
    )
    op.drop_index(
        op.f("ix_scheduler_endpoint_polling_history_cron_id"),
        table_name="endpoint_polling_history",
        schema="scheduler",
    )
    op.create_index(
        op.f("ix_endpoint_polling_history_tracked_value"),
        "endpoint_polling_history",
        ["tracked_value"],
        unique=False,
        schema="scheduler",
    )
    op.create_index(
        op.f("ix_endpoint_polling_history_id"), "endpoint_polling_history", ["id"], unique=False, schema="scheduler"
    )
    op.create_index(
        op.f("ix_endpoint_polling_history_cron_id"),
        "endpoint_polling_history",
        ["cron_id"],
        unique=False,
        schema="scheduler",
    )
    # ### end Alembic commands ###
