"""add cost table

Revision ID: 2a849385353a
Revises: b0ba5107a7e3
Create Date: 2025-11-20 12:01:46.207974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as psql


# revision identifiers, used by Alembic.
revision: str = "2a849385353a"
down_revision: Union[str, None] = "b0ba5107a7e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.Enum("llm", "component", "parameter_value", name="entity_type"), nullable=True),
        sa.Column("credits_per_second", sa.Float(), nullable=True),
        sa.Column("credits_per_call", sa.Float(), nullable=True),
        sa.Column("credits_per_input_token", sa.Float(), nullable=True),
        sa.Column("credits_per_output_token", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_costs_id"), "costs", ["id"], unique=False)
    op.create_table(
        "usages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("credits_used", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usages_id"), "usages", ["id"], unique=False)
    op.create_index(op.f("ix_usages_project_id"), "usages", ["project_id"], unique=False)
    op.create_table(
        "organization_limits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("limit", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "year", "month", name="uq_organization_limit_year_month"),
    )
    op.create_index(op.f("ix_organization_limits_id"), "organization_limits", ["id"], unique=False)
    op.create_index(
        op.f("ix_organization_limits_organization_id"), "organization_limits", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_organization_limits_org_year_month",
        "organization_limits",
        ["organization_id", "year", "month"],
        unique=False,
    )
    op.create_table(
        "component_costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("component_version_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_version_id"],
            ["component_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["costs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("component_version_id"),
    )
    op.create_table(
        "llm_costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("llm_model_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["costs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_model_id"],
            ["llm_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("llm_model_id"),
    )
    op.create_table(
        "parameter_value_costs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("component_parameter_definition_id", sa.UUID(), nullable=True),
        sa.Column("parameter_value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_parameter_definition_id"],
            ["component_parameter_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["costs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parameter_value_costs")
    op.drop_table("llm_costs")
    op.drop_table("component_costs")
    op.drop_index("ix_organization_limits_org_year_month", table_name="organization_limits")
    op.drop_index(op.f("ix_organization_limits_organization_id"), table_name="organization_limits")
    op.drop_index(op.f("ix_organization_limits_id"), table_name="organization_limits")
    op.drop_table("organization_limits")
    op.drop_index(op.f("ix_usages_project_id"), table_name="usages")
    op.drop_index(op.f("ix_usages_id"), table_name="usages")
    op.drop_table("usages")
    op.drop_index(op.f("ix_costs_id"), table_name="costs")
    op.drop_table("costs")
    # Drop the enum type
    entity_type_enum = psql.ENUM("llm", "component", "parameter_value", name="entity_type")
    entity_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
