"""add default to port defintion

Revision ID: 300e0970e3b6
Revises: 7055cd620c33
Create Date: 2026-02-18 17:28:22.475088

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "300e0970e3b6"
down_revision: Union[str, None] = "7055cd620c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("port_definitions", sa.Column("default", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("port_definitions", "default")
    # ### end Alembic commands ###
