"""remove organization token limit

Revision ID: 3519709bead8
Revises: 62d077615136
Create Date: 2025-12-10 16:16:32.560376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3519709bead8"
down_revision: Union[str, None] = "62d077615136"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_traces_organization_usage_organization_id"), table_name="organization_usage", schema="traces"
    )
    op.drop_table("organization_usage", schema="traces")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_usage",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("total_tokens", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_usage_pkey")),
        schema="traces",
    )
    op.create_index(
        op.f("ix_traces_organization_usage_organization_id"),
        "organization_usage",
        ["organization_id"],
        unique=False,
        schema="traces",
    )
    # ### end Alembic commands ###
