"""Add index for quality assurance

Revision ID: 3f8319d78154
Revises: cfe3267603c1
Create Date: 2025-12-10 18:32:52.351964

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f8319d78154"
down_revision: Union[str, None] = "cfe3267603c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: add the column as nullable so we can backfill existing rows.
    op.add_column("input_groundtruth", sa.Column("position", sa.Integer(), nullable=True), schema="quality_assurance")

    # Step 2: backfill position per dataset ordered by created_at (with id as stable tiebreaker).
    # Using a window function to derive a deterministic 1-based position.
    op.execute(
        sa.text(
            """
            UPDATE quality_assurance.input_groundtruth AS ig
            SET "position" = sub.idx
            FROM (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY dataset_id
                        ORDER BY created_at ASC, id ASC
                    ) AS idx
                FROM quality_assurance.input_groundtruth
            ) AS sub
            WHERE sub.id = ig.id
            """
        )
    )

    # Step 3: enforce not-null and uniqueness per dataset.
    op.alter_column("input_groundtruth", "position", schema="quality_assurance", nullable=False)
    op.create_unique_constraint(
        "uq_input_groundtruth_dataset_position",
        "input_groundtruth",
        ["dataset_id", "position"],
        schema="quality_assurance",
    )
    # Step 4: add check constraint to ensure position >= 1
    op.execute(
        sa.text(
            """
            ALTER TABLE quality_assurance.input_groundtruth
            ADD CONSTRAINT ck_input_groundtruth_position_positive
            CHECK (position >= 1)
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_input_groundtruth_position_positive", "input_groundtruth", schema="quality_assurance", type_="check"
    )
    op.drop_constraint(
        "uq_input_groundtruth_dataset_position", "input_groundtruth", schema="quality_assurance", type_="unique"
    )
    op.drop_column("input_groundtruth", "position", schema="quality_assurance")
    # ### end Alembic commands ###
