"""add cron to CallType

Revision ID: 4071a252013a
Revises: b81c2e3a4d5e
Create Date: 2026-03-10 11:03:38.203036

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4071a252013a"
down_revision: Union[str, None] = "b81c2e3a4d5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE call_type ADD VALUE IF NOT EXISTS 'cron'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
