"""Add component globals table and base_components column to components

Revision ID: 44a8ee9bc189
Revises: c565c7904a64
Create Date: 2025-09-25 18:25:13.700103

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44a8ee9bc189"
down_revision: Union[str, None] = "c565c7904a64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "component_global_parameters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("parameter_definition_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parameter_definition_id"], ["component_parameter_definitions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_component_global_parameters_id"), "component_global_parameters", ["id"], unique=False)
    op.create_index(
        op.f("ix_component_global_parameters_parameter_definition_id"),
        "component_global_parameters",
        ["parameter_definition_id"],
        unique=False,
    )
    op.create_index(
        "uq_comp_global_param_list",
        "component_global_parameters",
        ["component_id", "parameter_definition_id", "order"],
        unique=True,
        postgresql_where=sa.text('"order" IS NOT NULL'),
    )
    op.create_index(
        "uq_comp_global_param_scalar",
        "component_global_parameters",
        ["component_id", "parameter_definition_id"],
        unique=True,
        postgresql_where=sa.text('"order" IS NULL'),
    )
    op.add_column("components", sa.Column("base_component", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("components", "base_component")
    op.drop_index(
        "uq_comp_global_param_scalar",
        table_name="component_global_parameters",
        postgresql_where=sa.text('"order" IS NULL'),
    )
    op.drop_index(
        "uq_comp_global_param_list",
        table_name="component_global_parameters",
        postgresql_where=sa.text('"order" IS NOT NULL'),
    )
    op.drop_index(
        op.f("ix_component_global_parameters_parameter_definition_id"), table_name="component_global_parameters"
    )
    op.drop_index(op.f("ix_component_global_parameters_id"), table_name="component_global_parameters")
    op.drop_table("component_global_parameters")
    # ### end Alembic commands ###
