"""add attributes to data sources

Revision ID: 51f924d80447
Revises: 0d0db05d4dac
Create Date: 2025-08-27 11:56:16.894900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f924d80447'
down_revision: Union[str, None] = '0d0db05d4dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('attributes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'attributes')
    # ### end Alembic commands ###
