"""add version_name, tag_name, change_log to graph runner

Revision ID: 558db5695d27
Revises: c4aa0d13832e
Create Date: 2025-10-09 11:28:02.101277

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "558db5695d27"
down_revision: Union[str, None] = "c4aa0d13832e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("graph_runners", sa.Column("version_name", sa.String(), nullable=True))
    op.add_column("graph_runners", sa.Column("change_log", sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Data migration: strip leading 'v'/'V' from tag_version and populate tag_name
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE graph_runners
            SET tag_version = SUBSTRING(tag_version FROM 2)
            WHERE tag_version ~ '^[vV][0-9]+\\.[0-9]+\\.[0-9]+$'
            """
        )
    )


def downgrade() -> None:
    # Data migration: add 'v' back to tag_version
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE graph_runners
            SET tag_version = 'v' || tag_version
            WHERE tag_version ~ '^[0-9]+\\.[0-9]+\\.[0-9]+$'
            """
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("graph_runners", "change_log")
    op.drop_column("graph_runners", "version_name")
    # ### end Alembic commands ###
