"""add_evaluations_schema_in_ada_backend_and_question_answer_table

Revision ID: 69c499277cc7
Revises: 80118747a315
Create Date: 2025-07-21 14:20:49.986165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69c499277cc7"
down_revision: Union[str, None] = "80118747a315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the evaluations schema first
    op.execute("CREATE SCHEMA IF NOT EXISTS evaluations")

    op.create_table(
        "questions_answers",
        sa.Column("id", sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()")),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("groundtruth", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="evaluations",
    )
    op.create_index(
        op.f("ix_evaluations_questions_answers_id"), "questions_answers", ["id"], unique=False, schema="evaluations"
    )
    op.create_index(
        op.f("ix_evaluations_questions_answers_organization_id"),
        "questions_answers",
        ["organization_id"],
        unique=False,
        schema="evaluations",
    )
    op.create_index(
        op.f("ix_evaluations_questions_answers_project_id"),
        "questions_answers",
        ["project_id"],
        unique=False,
        schema="evaluations",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_evaluations_questions_answers_project_id"), table_name="questions_answers", schema="evaluations"
    )
    op.drop_index(
        op.f("ix_evaluations_questions_answers_organization_id"), table_name="questions_answers", schema="evaluations"
    )
    op.drop_index(op.f("ix_evaluations_questions_answers_id"), table_name="questions_answers", schema="evaluations")
    op.drop_table("questions_answers", schema="evaluations")

    # Drop the evaluations schema (only if it's empty)
    op.execute("DROP SCHEMA IF EXISTS evaluations CASCADE")
    # ### end Alembic commands ###
