"""Add is_advanced to port definitions

Revision ID: 6c3f812c5752
Revises: a1b2c3d4e5f7
Create Date: 2026-02-20 12:14:04.143434

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c3f812c5752"
down_revision: Union[str, None] = "a1b2c3d4e5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("port_definitions", sa.Column("is_advanced", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("port_definitions", "is_advanced")
    # ### end Alembic commands ###
