"""add quality assurance metadata tables

Revision ID: 7055cd620c33
Revises: 67ec7c0706ec
Create Date: 2026-02-11 12:03:00.685334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7055cd620c33'
down_revision: Union[str, None] = '67ec7c0706ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_dataset_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('column_display_position', sa.Integer(), nullable=False),
    sa.CheckConstraint('column_display_position >= 0', name='ck_qa_metadata_column_position_non_negative'),
    sa.ForeignKeyConstraint(['dataset_id'], ['quality_assurance.dataset_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'column_display_position', name='uq_qa_metadata_dataset_column_position'),
    sa.UniqueConstraint('dataset_id', 'column_id', name='uq_qa_metadata_dataset_column_id'),
    schema='quality_assurance'
    )
    op.create_index(op.f('ix_quality_assurance_qa_dataset_metadata_dataset_id'), 'qa_dataset_metadata', ['dataset_id'], unique=False, schema='quality_assurance')
    op.create_index(op.f('ix_quality_assurance_qa_dataset_metadata_id'), 'qa_dataset_metadata', ['id'], unique=False, schema='quality_assurance')
    op.add_column('input_groundtruth', sa.Column('custom_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='quality_assurance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_groundtruth', 'custom_columns', schema='quality_assurance')
    op.drop_index(op.f('ix_quality_assurance_qa_dataset_metadata_id'), table_name='qa_dataset_metadata', schema='quality_assurance')
    op.drop_index(op.f('ix_quality_assurance_qa_dataset_metadata_dataset_id'), table_name='qa_dataset_metadata', schema='quality_assurance')
    op.drop_table('qa_dataset_metadata', schema='quality_assurance')
    # ### end Alembic commands ###
