"""add agents

Revision ID: 79e3872b3b03
Revises: c565c7904a64
Create Date: 2025-09-25 11:09:23.789272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79e3872b3b03"
down_revision: Union[str, None] = "c565c7904a64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


project_type_enum = sa.Enum("agent", "workflow", name="project_type")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    project_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("projects", sa.Column("type", project_type_enum, nullable=True))
    op.execute("UPDATE projects SET type = 'workflow' WHERE type IS NULL")
    op.alter_column("projects", "type", nullable=False)

    op.create_table(
        "agent_projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workflow_projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
        INSERT INTO workflow_projects (id)
        SELECT id FROM projects WHERE type = 'workflow'
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "type")

    project_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_table("workflow_projects")
    op.drop_table("agent_projects")
    # ### end Alembic commands ###
