"""rename credits per unit and remove year month from limit

Revision ID: 8279e65a01dc
Revises: 2b410fd2fb0d
Create Date: 2025-12-09 16:35:11.738388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8279e65a01dc"
down_revision: Union[str, None] = "2b410fd2fb0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "costs",
        sa.Column("credits_per_unit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="credits",
    )
    op.drop_column("costs", "credits_per_second", schema="credits")
    op.drop_constraint(
        op.f("uq_organization_limit_year_month"), "organization_limits", schema="credits", type_="unique"
    )
    op.create_unique_constraint("uq_organization_limit", "organization_limits", ["organization_id"], schema="credits")
    op.drop_column("organization_limits", "month", schema="credits")
    op.drop_column("organization_limits", "year", schema="credits")
    op.add_column(
        "span_usages",
        sa.Column("credits_per_unit", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="credits",
    )
    op.drop_column("span_usages", "credits_per_second", schema="credits")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "span_usages",
        sa.Column("credits_per_second", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        schema="credits",
    )
    op.drop_column("span_usages", "credits_per_unit", schema="credits")
    op.add_column(
        "organization_limits", sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False), schema="credits"
    )
    op.add_column(
        "organization_limits", sa.Column("month", sa.INTEGER(), autoincrement=False, nullable=False), schema="credits"
    )
    op.drop_constraint("uq_organization_limit", "organization_limits", schema="credits", type_="unique")
    op.create_unique_constraint(
        op.f("uq_organization_limit_year_month"),
        "organization_limits",
        ["organization_id", "year", "month"],
        schema="credits",
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "costs",
        sa.Column("credits_per_second", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        schema="credits",
    )
    op.drop_column("costs", "credits_per_unit", schema="credits")
    # ### end Alembic commands ###
