"""rename credits_per to credits_per and remove year month from limit

Revision ID: 8279e65a01dc
Revises: e18942767d31
Create Date: 2025-12-09 16:35:11.738388

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8279e65a01dc"
down_revision: Union[str, None] = "e18942767d31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "costs",
        sa.Column("credits_per", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="credits",
    )
    op.drop_column("costs", "credits_per_second", schema="credits")
    op.drop_constraint(
        op.f("uq_organization_limit_year_month"), "organization_limits", schema="credits", type_="unique"
    )
    op.create_unique_constraint("uq_organization_limit", "organization_limits", ["organization_id"], schema="credits")
    op.drop_column("organization_limits", "month", schema="credits")
    op.drop_column("organization_limits", "year", schema="credits")
    op.add_column(
        "span_usages",
        sa.Column("credits_per", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="credits",
    )
    op.drop_column("span_usages", "credits_per_second", schema="credits")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "span_usages",
        sa.Column("credits_per_second", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        schema="credits",
    )
    op.drop_column("span_usages", "credits_per", schema="credits")

    # Add year and month columns as nullable first
    op.add_column(
        "organization_limits", sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=True), schema="credits"
    )
    op.add_column(
        "organization_limits", sa.Column("month", sa.INTEGER(), autoincrement=False, nullable=True), schema="credits"
    )

    # Populate year and month with current year/month for existing rows
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            UPDATE credits.organization_limits
            SET year = EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER,
                month = EXTRACT(MONTH FROM CURRENT_DATE)::INTEGER
            WHERE year IS NULL OR month IS NULL
            """
        )
    )

    # Now make them NOT NULL
    op.alter_column("organization_limits", "year", nullable=False, schema="credits")
    op.alter_column("organization_limits", "month", nullable=False, schema="credits")

    op.drop_constraint("uq_organization_limit", "organization_limits", schema="credits", type_="unique")
    op.create_unique_constraint(
        op.f("uq_organization_limit_year_month"),
        "organization_limits",
        ["organization_id", "year", "month"],
        schema="credits",
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "costs",
        sa.Column("credits_per_second", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        schema="credits",
    )
    op.drop_column("costs", "credits_per", schema="credits")
    # ### end Alembic commands ###
