"""new icon parameter in class Component

Revision ID: 8ae8246c0768
Revises: 79e3872b3b03
Create Date: 2025-10-06 11:15:58.215024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ae8246c0768"
down_revision: Union[str, None] = "79e3872b3b03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("components", sa.Column("icon", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("components", "icon")
    # ### end Alembic commands ###
