"""add attributes to data sources

Revision ID: 8c58afb2412e
Revises: 0d0db05d4dac
Create Date: 2025-08-29 16:07:17.437400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c58afb2412e"
down_revision: Union[str, None] = "0d0db05d4dac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = "org_secret_type"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_sources", sa.Column("attributes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###

    # Add database_url to existing org_secret_type enum
    op.execute("ALTER TYPE org_secret_type ADD VALUE IF NOT EXISTS 'database_url'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "attributes")
    # ### end Alembic commands ###
