"""add_project_options_table

Revision ID: 8c87a3fea6d4
Revises: 8daad1874818
Create Date: 2026-02-08 12:22:33.868138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c87a3fea6d4'
down_revision: Union[str, None] = '8daad1874818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('option_key', sa.String(length=255), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'option_key', name='uq_project_option_key')
    )
    op.create_index(op.f('ix_project_options_id'), 'project_options', ['id'], unique=False)
    op.create_index(op.f('ix_project_options_project_id'), 'project_options', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_options_project_id'), table_name='project_options')
    op.drop_index(op.f('ix_project_options_id'), table_name='project_options')
    op.drop_table('project_options')
    # ### end Alembic commands ###
