"""remove companion url from projects

Revision ID: 8cc2f22a492e
Revises: 79e3872b3b03
Create Date: 2025-10-08 18:03:55.039316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cc2f22a492e"
down_revision: Union[str, None] = "79e3872b3b03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "companion_image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("companion_image_url", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
