"""add oauth connection ui component enum value

Revision ID: 8daad1874818
Revises: fe1c665d7821
Create Date: 2026-02-04 22:48:51.018145

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8daad1874818"
down_revision: Union[str, None] = "fe1c665d7821"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new value to ui_component enum
    op.execute("ALTER TYPE ui_component ADD VALUE IF NOT EXISTS 'OAuthConnection'")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
