"""remove update_existing, add additional_timestap_column in attributes

Revision ID: 9de056f530fc
Revises: 8b393d7c2c4b
Create Date: 2025-09-12 11:16:06.240685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9de056f530fc"
down_revision: Union[str, None] = "8b393d7c2c4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source_attributes", sa.Column("additional_timestamp_column_name", sa.String(), nullable=True))
    op.drop_column("source_attributes", "update_existing")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column("source_attributes", sa.Column("update_existing", sa.BOOLEAN(), nullable=True))
    # Set a default value for existing rows
    op.execute("UPDATE source_attributes SET update_existing = false WHERE update_existing IS NULL")
    # Make the column NOT NULL
    op.alter_column("source_attributes", "update_existing", nullable=False)
    op.drop_column("source_attributes", "additional_timestamp_column_name")
    # ### end Alembic commands ###
