"""nouvel element icon dans classe Component

Revision ID: a07730e953c1
Revises: 1eb7c34db2a7
Create Date: 2025-10-03 14:51:14.984373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07730e953c1'
down_revision: Union[str, None] = '1eb7c34db2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'icon')
    # ### end Alembic commands ###
