"""Add global secrets table

Revision ID: a0b2cb501819
Revises: 44a8ee9bc189
Create Date: 2025-09-26 11:44:59.761469

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0b2cb501819"
down_revision: Union[str, None] = "44a8ee9bc189"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("encrypted_secret", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_global_secrets_id"), "global_secrets", ["id"], unique=False)
    op.create_index(op.f("ix_global_secrets_key"), "global_secrets", ["key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_global_secrets_key"), table_name="global_secrets")
    op.drop_index(op.f("ix_global_secrets_id"), table_name="global_secrets")
    op.drop_table("global_secrets")
    # ### end Alembic commands ###
