"""add_llm_judge_table

Revision ID: a12dd029963e
Revises: a4576629806f
Create Date: 2025-11-18 11:26:28.183062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a12dd029963e"
down_revision: Union[str, None] = "a4576629806f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_judges",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evaluation_type", sa.Enum("boolean", "score", "free", name="evaluation_type"), nullable=False),
        sa.Column("llm_model_reference", sa.String(), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="quality_assurance",
    )
    op.create_index(
        op.f("ix_quality_assurance_llm_judges_id"), "llm_judges", ["id"], unique=False, schema="quality_assurance"
    )
    op.create_index(
        op.f("ix_quality_assurance_llm_judges_project_id"),
        "llm_judges",
        ["project_id"],
        unique=False,
        schema="quality_assurance",
    )
    op.drop_constraint(op.f("span_messages_span_id_fkey"), "span_messages", schema="traces", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("span_messages_span_id_fkey"),
        "span_messages",
        "spans",
        ["span_id"],
        ["span_id"],
        source_schema="traces",
        referent_schema="traces",
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_quality_assurance_llm_judges_project_id"), table_name="llm_judges", schema="quality_assurance"
    )
    op.drop_index(op.f("ix_quality_assurance_llm_judges_id"), table_name="llm_judges", schema="quality_assurance")
    op.drop_table("llm_judges", schema="quality_assurance")
    # ### end Alembic commands ###
