"""Add encrypted_raw_key column to api_keys table for cron jobs

Revision ID: a4e95a3b79ca
Revises: f9c9976e066e
Create Date: 2025-07-25 17:27:41.742503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4e95a3b79ca"
down_revision: Union[str, None] = "f9c9976e066e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("encrypted_raw_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up any existing API keys with encrypted_raw_key (old cron API keys)
    op.execute("DELETE FROM api_keys WHERE encrypted_raw_key IS NOT NULL")
    op.drop_column("api_keys", "encrypted_raw_key")
    # ### end Alembic commands ###
