"""add group parameters tables for components version

Revision ID: a86270305bab
Revises: f1e79aa97806
Create Date: 2025-10-24 13:12:55.426910

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a86270305bab"
down_revision: Union[str, None] = "f1e79aa97806"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameter_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "component_parameter_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("component_version_id", sa.UUID(), nullable=False),
        sa.Column("parameter_group_id", sa.UUID(), nullable=False),
        sa.Column("group_order_within_component", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["component_version_id"], ["component_versions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parameter_group_id"],
            ["parameter_groups.id"],
            name="fk_component_parameter_groups_parameter_group_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("component_version_id", "parameter_group_id", name="uq_component_version_parameter_group"),
    )
    op.add_column("component_parameter_definitions", sa.Column("parameter_group_id", sa.UUID(), nullable=True))
    op.add_column(
        "component_parameter_definitions", sa.Column("parameter_order_within_group", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_component_parameter_definitions_parameter_group_id",
        "component_parameter_definitions",
        "parameter_groups",
        ["parameter_group_id"],
        ["id"],
    )
    op.alter_column("graph_runners", "change_log", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("graph_runners", "change_log", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.drop_constraint(
        "fk_component_parameter_definitions_parameter_group_id", "component_parameter_definitions", type_="foreignkey"
    )
    op.drop_column("component_parameter_definitions", "parameter_order_within_group")
    op.drop_column("component_parameter_definitions", "parameter_group_id")
    op.drop_table("component_parameter_groups")
    op.drop_table("parameter_groups")
    # ### end Alembic commands ###
