"""add integrations

Revision ID: a8a3795c60ea
Revises: 80118747a315
Create Date: 2025-07-16 16:24:12.713264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8a3795c60ea"
down_revision: Union[str, None] = "80118747a315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "component_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("component_instance_id", sa.UUID(), nullable=True),
        sa.Column("integration_id", sa.UUID(), nullable=True),
        sa.Column("encrypted_access_token", sa.String(), nullable=True),
        sa.Column("encrypted_refresh_token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_instance_id"],
            ["component_instances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("components", sa.Column("integration_id", sa.UUID(), nullable=True))
    op.create_foreign_key("components_integration_id_fkey", "components", "integrations", ["integration_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("components_integration_id_fkey", "components", type_="foreignkey")
    op.drop_column("components", "integration_id")
    op.drop_table("component_integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
