"""add integrations

Revision ID: af554923bffe
Revises: 80118747a315
Create Date: 2025-07-18 14:26:52.481146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af554923bffe"
down_revision: Union[str, None] = "80118747a315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("integration_id", sa.UUID(), nullable=True),
        sa.Column("encrypted_access_token", sa.String(), nullable=True),
        sa.Column("encrypted_refresh_token", sa.String(), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.Column("token_last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("components", sa.Column("integration_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fkey_components_integration_id", "components", "integrations", ["integration_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fkey_components_integration_id", "components", type_="foreignkey")
    op.drop_column("components", "integration_id")
    op.drop_table("project_integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
