"""Add group parameters table

Revision ID: b82b2dc24cf3
Revises: 558db5695d27
Create Date: 2025-10-23 11:10:48.922968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b82b2dc24cf3"
down_revision: Union[str, None] = "558db5695d27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameter_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "component_parameter_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("component_id", sa.UUID(), nullable=False),
        sa.Column("parameter_group_id", sa.UUID(), nullable=False),
        sa.Column("group_order_within_component", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["component_id"], ["components.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parameter_group_id"],
            ["parameter_groups.id"],
            name="fk_component_parameter_groups_parameter_group_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("component_id", "parameter_group_id", name="uq_component_parameter_group"),
    )
    op.add_column("component_parameter_definitions", sa.Column("parameter_group_id", sa.UUID(), nullable=True))
    op.add_column(
        "component_parameter_definitions", sa.Column("parameter_order_within_group", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_component_parameter_definitions_parameter_group_id",
        "component_parameter_definitions",
        "parameter_groups",
        ["parameter_group_id"],
        ["id"],
    )
    op.alter_column("graph_runners", "change_log", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("graph_runners", "change_log", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.drop_constraint(
        "fk_component_parameter_definitions_parameter_group_id", "component_parameter_definitions", type_="foreignkey"
    )
    op.drop_column("component_parameter_definitions", "parameter_order_within_group")
    op.drop_column("component_parameter_definitions", "parameter_group_id")
    op.drop_table("component_parameter_groups")
    op.drop_table("parameter_groups")
    # ### end Alembic commands ###
