"""remove constraint on node

Revision ID: c2e594ae12bd
Revises: 4c00161c3d6c
Create Date: 2025-10-15 18:23:38.670666

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c2e594ae12bd"
down_revision: Union[str, None] = "4c00161c3d6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_graph_runner_node"), "graph_runner_nodes", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_graph_runner_node"),
        "graph_runner_nodes",
        ["graph_runner_id", "node_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
