"""name not unique in tool description table

Revision ID: c4aa0d13832e
Revises: 8cc2f22a492e
Create Date: 2025-10-10 14:25:49.736482

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4aa0d13832e"
down_revision: Union[str, None] = "8cc2f22a492e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tool_descriptions_name_key"), "tool_descriptions", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("tool_descriptions_name_key"), "tool_descriptions", ["name"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
