"""new_code_ui_component

Revision ID: cb22ac4f4a42
Revises: b7e8f9a0c1d2
Create Date: 2026-02-11 15:58:43.941356

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cb22ac4f4a42'
down_revision: Union[str, None] = 'b7e8f9a0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'Code' value to UIComponent enum
    op.execute("ALTER TYPE ui_component ADD VALUE IF NOT EXISTS 'Code'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
