"""add ui metadata to port definitions

Revision ID: cfe3267603c1
Revises: 8279e65a01dc
Create Date: 2025-12-09 10:18:57.728732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ada_backend.database.utils import create_enum_if_not_exists

# revision identifiers, used by Alembic.
revision: str = "cfe3267603c1"
down_revision: Union[str, None] = "8279e65a01dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    enum_values = [
        "Autocomplete",
        "Checkbox",
        "Combobox",
        "Date Time Picker",
        "Editors",
        "File Input",
        "Radio",
        "Custom Input",
        "Range Slider",
        "Rating",
        "Select",
        "Slider",
        "Switch",
        "Textarea",
        "Textfield",
        "FileUpload",
        "JSON Builder",
    ]
    create_enum_if_not_exists(bind, enum_values=enum_values, enum_name="ui_component")

    ui_component_enum = postgresql.ENUM(name="ui_component", create_type=False)
    op.add_column("port_definitions", sa.Column("ui_component", ui_component_enum, nullable=True))
    op.add_column(
        "port_definitions",
        sa.Column("ui_component_properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("port_definitions", "ui_component_properties")
    op.drop_column("port_definitions", "ui_component")
    # ### end Alembic commands ###
