"""add attributes table

Revision ID: d4a5151de832
Revises: 0d0db05d4dac
Create Date: 2025-08-29 19:54:30.089824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4a5151de832"
down_revision: Union[str, None] = "0d0db05d4dac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_attributes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("list_of_files_from_local_folder", sa.JSON(), nullable=True),
        sa.Column("folder_id", sa.String(), nullable=True),
        sa.Column("source_db_url", sa.UUID(), nullable=True),
        sa.Column("source_table_name", sa.String(), nullable=True),
        sa.Column("id_column_name", sa.String(), nullable=True),
        sa.Column("text_column_names", sa.JSON(), nullable=True),
        sa.Column("source_schema_name", sa.String(), nullable=True),
        sa.Column("chunk_size", sa.Integer(), nullable=True),
        sa.Column("chunk_overlap", sa.Integer(), nullable=True),
        sa.Column("metadata_column_names", sa.JSON(), nullable=True),
        sa.Column("timestamp_column_name", sa.String(), nullable=True),
        sa.Column("url_pattern", sa.String(), nullable=True),
        sa.Column("update_existing", sa.Boolean(), nullable=False),
        sa.Column("query_filter", sa.String(), nullable=True),
        sa.Column("timestamp_filter", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["source_db_url"], ["organization_secrets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["data_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_attributes_id"), "source_attributes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_attributes_id"), table_name="source_attributes")
    op.drop_table("source_attributes")
    # ### end Alembic commands ###
