"""add_django_workflow_table_and_api_key_cron_job

Revision ID: db17747e6704
Revises: 80118747a315
Create Date: 2025-07-23 15:39:57.253877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db17747e6704'
down_revision: Union[str, None] = '80118747a315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('django_celery_beat_crontabschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.String(length=240), nullable=False),
    sa.Column('hour', sa.String(length=96), nullable=False),
    sa.Column('day_of_week', sa.String(length=64), nullable=False),
    sa.Column('day_of_month', sa.String(length=124), nullable=False),
    sa.Column('month_of_year', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_django_celery_beat_crontabschedule_id'), 'django_celery_beat_crontabschedule', ['id'], unique=False)
    op.create_table('django_celery_beat_periodictasks',
    sa.Column('ident', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ident')
    )
    op.create_table('django_celery_beat_periodictask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('crontab_id', sa.Integer(), nullable=True),
    sa.Column('args', sa.Text(), nullable=False),
    sa.Column('kwargs', sa.Text(), nullable=False),
    sa.Column('queue', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=200), nullable=True),
    sa.Column('routing_key', sa.String(length=200), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_run_count', sa.Integer(), nullable=False),
    sa.Column('date_changed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['crontab_id'], ['django_celery_beat_crontabschedule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_django_celery_beat_periodictask_id'), 'django_celery_beat_periodictask', ['id'], unique=False)
    op.add_column('api_keys', sa.Column('encrypted_raw_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'encrypted_raw_key')
    op.drop_index(op.f('ix_django_celery_beat_periodictask_id'), table_name='django_celery_beat_periodictask')
    op.drop_table('django_celery_beat_periodictask')
    op.drop_table('django_celery_beat_periodictasks')
    op.drop_index(op.f('ix_django_celery_beat_crontabschedule_id'), table_name='django_celery_beat_crontabschedule')
    op.drop_table('django_celery_beat_crontabschedule')
    # ### end Alembic commands ###
