"""

Revision ID: e0e47d35b398
Revises: abc123def456
Create Date: 2026-01-14 10:21:37.740428

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e0e47d35b398'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'display_order')
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
