"""add_llm_judge_table

Revision ID: f1435acd5412
Revises: 88dcf82ab86
Create Date: 2025-11-14 16:25:52.034737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1435acd5412"
down_revision: Union[str, None] = "88dcf82ab86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_judges",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evaluation_type", sa.Enum("boolean", "score", name="evaluation_type"), nullable=False),
        sa.Column("llm_model_reference", sa.String(), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="quality_assurance",
    )
    op.create_index(
        op.f("ix_quality_assurance_llm_judges_id"), "llm_judges", ["id"], unique=False, schema="quality_assurance"
    )
    op.create_index(
        op.f("ix_quality_assurance_llm_judges_project_id"),
        "llm_judges",
        ["project_id"],
        unique=False,
        schema="quality_assurance",
    )
    op.create_table(
        "judge_evaluations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("judge_id", sa.UUID(), nullable=False),
        sa.Column("version_output_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_llm_response", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["judge_id"], ["quality_assurance.llm_judges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["version_output_id"], ["quality_assurance.version_output.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("judge_id", "version_output_id", name="uq_judge_version_output"),
        schema="quality_assurance",
    )
    op.create_index(
        op.f("ix_quality_assurance_judge_evaluations_id"),
        "judge_evaluations",
        ["id"],
        unique=False,
        schema="quality_assurance",
    )
    op.create_index(
        op.f("ix_quality_assurance_judge_evaluations_judge_id"),
        "judge_evaluations",
        ["judge_id"],
        unique=False,
        schema="quality_assurance",
    )
    op.create_index(
        op.f("ix_quality_assurance_judge_evaluations_version_output_id"),
        "judge_evaluations",
        ["version_output_id"],
        unique=False,
        schema="quality_assurance",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quality_assurance_judge_evaluations_version_output_id"),
        table_name="judge_evaluations",
        schema="quality_assurance",
    )
    op.drop_index(
        op.f("ix_quality_assurance_judge_evaluations_judge_id"),
        table_name="judge_evaluations",
        schema="quality_assurance",
    )
    op.drop_index(
        op.f("ix_quality_assurance_judge_evaluations_id"), table_name="judge_evaluations", schema="quality_assurance"
    )
    op.drop_table("judge_evaluations", schema="quality_assurance")
    op.drop_index(
        op.f("ix_quality_assurance_llm_judges_project_id"), table_name="llm_judges", schema="quality_assurance"
    )
    op.drop_index(op.f("ix_quality_assurance_llm_judges_id"), table_name="llm_judges", schema="quality_assurance")
    op.drop_table("llm_judges", schema="quality_assurance")
    # ### end Alembic commands ###
