"""add component_instance_id and model_id as columns

Revision ID: f2c95397dc15
Revises: 2a849385353a
Create Date: 2025-11-27 12:22:02.950658

"""

from typing import Sequence, Union
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

LOGGER = logging.getLogger(__name__)


# revision identifiers, used by Alembic.
revision: str = "f2c95397dc15"
down_revision: Union[str, None] = "2a849385353a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spans", sa.Column("component_instance_id", sa.UUID(), nullable=True), schema="traces")
    op.add_column("spans", sa.Column("model_id", sa.UUID(), nullable=True), schema="traces")
    op.create_index(
        op.f("ix_traces_spans_component_instance_id"),
        "spans",
        ["component_instance_id"],
        unique=False,
        schema="traces",
    )
    op.create_index(op.f("ix_traces_spans_model_id"), "spans", ["model_id"], unique=False, schema="traces")
    op.create_foreign_key(
        "fk_spans_component_instance_id",
        "spans",
        "component_instances",
        ["component_instance_id"],
        ["id"],
        source_schema="traces",
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_spans_model_id",
        "spans",
        "llm_models",
        ["model_id"],
        ["id"],
        source_schema="traces",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Data migration: Extract component_instance_id from attributes and move to column
    connection = op.get_bind()

    LOGGER.info("Extracting component_instance_id from attributes...")
    update_query = text(
        """
        UPDATE traces.spans
        SET component_instance_id = CAST(attributes->>'component_instance_id' AS UUID)
        WHERE attributes ? 'component_instance_id'
          AND attributes->>'component_instance_id' IS NOT NULL
          AND attributes->>'component_instance_id' != ''
          AND attributes->>'component_instance_id' != 'None'
          AND attributes->>'component_instance_id' != 'null'
          AND EXISTS (
            SELECT 1 FROM component_instances 
            WHERE id = CAST(attributes->>'component_instance_id' AS UUID)
          )
    """
    )

    result = connection.execute(update_query)
    LOGGER.info(f"Updated {result.rowcount} rows with component_instance_id")

    LOGGER.info("Removing component_instance_id from attributes...")
    remove_query = text(
        """
        UPDATE traces.spans
        SET attributes = attributes - 'component_instance_id'
        WHERE attributes ? 'component_instance_id'
    """
    )

    result = connection.execute(remove_query)
    LOGGER.info(f"Removed component_instance_id from attributes in {result.rowcount} rows")


def downgrade() -> None:
    # Data migration: Restore component_instance_id back to attributes before dropping column
    connection = op.get_bind()

    LOGGER.info("Restoring component_instance_id to attributes...")
    restore_query = text(
        """
        UPDATE traces.spans
        SET attributes = jsonb_set(
            attributes,
            '{component_instance_id}',
            to_jsonb(component_instance_id::text),
            true
        )
        WHERE component_instance_id IS NOT NULL
    """
    )

    result = connection.execute(restore_query)
    LOGGER.info(f"Restored component_instance_id to attributes in {result.rowcount} rows")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_spans_component_instance_id", "spans", schema="traces", type_="foreignkey")
    op.drop_constraint("fk_spans_model_id", "spans", schema="traces", type_="foreignkey")
    op.drop_index(op.f("ix_traces_spans_model_id"), table_name="spans", schema="traces")
    op.drop_index(op.f("ix_traces_spans_component_instance_id"), table_name="spans", schema="traces")
    op.drop_column("spans", "model_id", schema="traces")
    op.drop_column("spans", "component_instance_id", schema="traces")
    # ### end Alembic commands ###
