"""Remove database_name from DataSources table

Revision ID: f35bfa8d86b7
Revises: 2795c830aa09
Create Date: 2025-05-30 11:12:14.765764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f35bfa8d86b7"
down_revision: Union[str, None] = "2795c830aa09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "database_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_sources", sa.Column("database_name", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
