"""add graph runner modification history

Revision ID: f44ef4de7468
Revises: f2c95397dc15
Create Date: 2025-01-27 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f44ef4de7468"
down_revision: Union[str, None] = "f2c95397dc15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_runner_modification_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_runner_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("modification_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_runner_id"],
            ["graph_runners.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_graph_runner_modification_history_id"),
        "graph_runner_modification_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_runner_modification_history_graph_runner_id"),
        "graph_runner_modification_history",
        ["graph_runner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_runner_modification_history_created_at"),
        "graph_runner_modification_history",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_graph_runner_modification_history_created_at"),
        table_name="graph_runner_modification_history",
    )
    op.drop_index(
        op.f("ix_graph_runner_modification_history_graph_runner_id"),
        table_name="graph_runner_modification_history",
    )
    op.drop_index(
        op.f("ix_graph_runner_modification_history_id"),
        table_name="graph_runner_modification_history",
    )
    op.drop_table("graph_runner_modification_history")
    # ### end Alembic commands ###

