"""add color to comp instance

Revision ID: f7ec948db993
Revises: 0d0db05d4dac
Create Date: 2025-08-01 12:52:38.299775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ec948db993'
down_revision: Union[str, None] = '0d0db05d4dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_instances', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('component_instances', 'color')
    # ### end Alembic commands ###
