"""Add port definitions and mappings tables

Revision ID: f94e9fdc03e4
Revises: c565c7904a64
Create Date: 2025-09-24 03:55:39.848809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f94e9fdc03e4'
down_revision: Union[str, None] = 'c565c7904a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cron_expr', sa.String(), nullable=False),
    sa.Column('tz', sa.String(), nullable=False),
    sa.Column('entrypoint', sa.Enum('agent_inference', 'dummy_print', name='cron_entrypoint'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduler'
    )
    op.create_index(op.f('ix_scheduler_cron_jobs_id'), 'cron_jobs', ['id'], unique=False, schema='scheduler')
    op.create_index(op.f('ix_scheduler_cron_jobs_organization_id'), 'cron_jobs', ['organization_id'], unique=False, schema='scheduler')
    op.create_table('dataset_project',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='quality_assurance'
    )
    op.create_index(op.f('ix_quality_assurance_dataset_project_id'), 'dataset_project', ['id'], unique=False, schema='quality_assurance')
    op.create_index(op.f('ix_quality_assurance_dataset_project_project_id'), 'dataset_project', ['project_id'], unique=False, schema='quality_assurance')
    op.create_table('cron_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cron_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('success', 'error', 'running', name='cron_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cron_id'], ['scheduler.cron_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='scheduler'
    )
    op.create_index(op.f('ix_scheduler_cron_runs_cron_id'), 'cron_runs', ['cron_id'], unique=False, schema='scheduler')
    op.create_index(op.f('ix_scheduler_cron_runs_id'), 'cron_runs', ['id'], unique=False, schema='scheduler')
    op.create_index(op.f('ix_scheduler_cron_runs_scheduled_for'), 'cron_runs', ['scheduled_for'], unique=False, schema='scheduler')
    op.create_table('port_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('port_type', sa.Enum('INPUT', 'OUTPUT', name='port_type'), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_groundtruth',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('input', sa.String(), nullable=False),
    sa.Column('groundtruth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['quality_assurance.dataset_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='quality_assurance'
    )
    op.create_index(op.f('ix_quality_assurance_input_groundtruth_dataset_id'), 'input_groundtruth', ['dataset_id'], unique=False, schema='quality_assurance')
    op.create_index(op.f('ix_quality_assurance_input_groundtruth_id'), 'input_groundtruth', ['id'], unique=False, schema='quality_assurance')
    op.create_table('port_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_runner_id', sa.UUID(), nullable=False),
    sa.Column('source_instance_id', sa.UUID(), nullable=False),
    sa.Column('source_port_name', sa.String(), nullable=False),
    sa.Column('target_instance_id', sa.UUID(), nullable=False),
    sa.Column('target_port_name', sa.String(), nullable=False),
    sa.Column('dispatch_strategy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['graph_runner_id'], ['graph_runners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_instance_id'], ['component_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_instance_id'], ['component_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version_output',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('input_id', sa.UUID(), nullable=False),
    sa.Column('output', sa.String(), nullable=False),
    sa.Column('version', sa.Enum('draft', 'production', name='env_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['quality_assurance.input_groundtruth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='quality_assurance'
    )
    op.create_index(op.f('ix_quality_assurance_version_output_id'), 'version_output', ['id'], unique=False, schema='quality_assurance')
    op.create_index(op.f('ix_quality_assurance_version_output_input_id'), 'version_output', ['input_id'], unique=False, schema='quality_assurance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_assurance_version_output_input_id'), table_name='version_output', schema='quality_assurance')
    op.drop_index(op.f('ix_quality_assurance_version_output_id'), table_name='version_output', schema='quality_assurance')
    op.drop_table('version_output', schema='quality_assurance')
    op.drop_table('port_mappings')
    op.drop_index(op.f('ix_quality_assurance_input_groundtruth_id'), table_name='input_groundtruth', schema='quality_assurance')
    op.drop_index(op.f('ix_quality_assurance_input_groundtruth_dataset_id'), table_name='input_groundtruth', schema='quality_assurance')
    op.drop_table('input_groundtruth', schema='quality_assurance')
    op.drop_table('port_definitions')
    op.drop_index(op.f('ix_scheduler_cron_runs_scheduled_for'), table_name='cron_runs', schema='scheduler')
    op.drop_index(op.f('ix_scheduler_cron_runs_id'), table_name='cron_runs', schema='scheduler')
    op.drop_index(op.f('ix_scheduler_cron_runs_cron_id'), table_name='cron_runs', schema='scheduler')
    op.drop_table('cron_runs', schema='scheduler')
    op.drop_index(op.f('ix_quality_assurance_dataset_project_project_id'), table_name='dataset_project', schema='quality_assurance')
    op.drop_index(op.f('ix_quality_assurance_dataset_project_id'), table_name='dataset_project', schema='quality_assurance')
    op.drop_table('dataset_project', schema='quality_assurance')
    op.drop_index(op.f('ix_scheduler_cron_jobs_organization_id'), table_name='cron_jobs', schema='scheduler')
    op.drop_index(op.f('ix_scheduler_cron_jobs_id'), table_name='cron_jobs', schema='scheduler')
    op.drop_table('cron_jobs', schema='scheduler')
    # ### end Alembic commands ###
