"""Add port definitions and mappings tables

Revision ID: f94e9fdc03e4
Revises: c565c7904a64
Create Date: 2025-09-24 03:55:39.848809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f94e9fdc03e4'
down_revision: Union[str, None] = 'c565c7904a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('port_type', sa.Enum('INPUT', 'OUTPUT', name='port_type'), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_runner_id', sa.UUID(), nullable=False),
    sa.Column('source_instance_id', sa.UUID(), nullable=False),
    sa.Column('source_port_name', sa.String(), nullable=False),
    sa.Column('target_instance_id', sa.UUID(), nullable=False),
    sa.Column('target_port_name', sa.String(), nullable=False),
    sa.Column('dispatch_strategy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['graph_runner_id'], ['graph_runners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_instance_id'], ['component_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_instance_id'], ['component_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('port_mappings')
    op.drop_table('port_definitions')
    # ### end Alembic commands ###
