"""add integrations

Revision ID: f9c9976e066e
Revises: 80118747a315
Create Date: 2025-07-18 17:18:40.953345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9c9976e066e"
down_revision: Union[str, None] = "80118747a315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "secret_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=True),
        sa.Column("encrypted_access_token", sa.String(), nullable=True),
        sa.Column("encrypted_refresh_token", sa.String(), nullable=True),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.Column("token_last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "integration_component_instance_relationships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("secret_integration_id", sa.UUID(), nullable=False),
        sa.Column("component_instance_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["component_instance_id"], ["component_instances.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["secret_integration_id"], ["secret_integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_integration_component_instance_relationships_id"),
        "integration_component_instance_relationships",
        ["id"],
        unique=False,
    )
    op.add_column("components", sa.Column("integration_id", sa.UUID(), nullable=True))
    op.create_foreign_key("fk_components_integration_id", "components", "integrations", ["integration_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_components_integration_id", "components", type_="foreignkey")
    op.drop_column("components", "integration_id")
    op.drop_index(
        op.f("ix_integration_component_instance_relationships_id"),
        table_name="integration_component_instance_relationships",
    )
    op.drop_table("integration_component_instance_relationships")
    op.drop_table("secret_integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###
