"""add version to global parameter

Revision ID: f9f8744c15e5
Revises: db6ec45f87f4
Create Date: 2025-10-08 14:40:26.213488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f8744c15e5'
down_revision: Union[str, None] = 'db6ec45f87f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_global_parameters', sa.Column('component_version_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('uq_comp_global_param_list'), table_name='component_global_parameters', postgresql_where='("order" IS NOT NULL)')
    op.create_index('uq_comp_global_param_list', 'component_global_parameters', ['component_version_id', 'parameter_definition_id', 'order'], unique=True, postgresql_where=sa.text('"order" IS NOT NULL'))
    op.drop_index(op.f('uq_comp_global_param_scalar'), table_name='component_global_parameters', postgresql_where='("order" IS NULL)')
    op.create_index('uq_comp_global_param_scalar', 'component_global_parameters', ['component_version_id', 'parameter_definition_id'], unique=True, postgresql_where=sa.text('"order" IS NULL'))
    op.drop_constraint(op.f('component_global_parameters_component_id_fkey'), 'component_global_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'component_global_parameters', 'component_versions', ['component_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('component_global_parameters', 'component_id')
    op.drop_constraint(op.f('uq_component_versions_component_id_id'), 'component_versions', type_='unique')
    op.create_index(op.f('ix_component_versions_id'), 'component_versions', ['id'], unique=False)
    op.add_column('components', sa.Column('description', sa.Text(), nullable=True))
    op.create_index('idx_current_by_component_stage', 'release_stage_to_current_version_mappings', ['component_id', 'release_stage'], unique=True)
    op.create_index(op.f('ix_release_stage_to_current_version_mappings_component_version_id'), 'release_stage_to_current_version_mappings', ['component_version_id'], unique=False)
    op.create_index(op.f('ix_release_stage_to_current_version_mappings_component_id'), 'release_stage_to_current_version_mappings', ['component_id'], unique=False)
    op.create_index(op.f('ix_release_stage_to_current_version_mappings_id'), 'release_stage_to_current_version_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_stage_to_current_version_mappings_id'), table_name='release_stage_to_current_version_mappings')
    op.drop_index(op.f('ix_release_stage_to_current_version_mappings_component_id'), table_name='release_stage_to_current_version_mappings')
    op.drop_index(op.f('ix_release_stage_to_current_version_mappings_component_version_id'), table_name='release_stage_to_current_version_mappings')
    op.drop_index('idx_current_by_component_stage', table_name='release_stage_to_current_version_mappings')
    op.drop_column('components', 'description')
    op.drop_index(op.f('ix_component_versions_id'), table_name='component_versions')
    op.create_unique_constraint(op.f('uq_component_versions_component_id_id'), 'component_versions', ['component_id', 'id'], postgresql_nulls_not_distinct=False)
    op.add_column('component_global_parameters', sa.Column('component_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'component_global_parameters', type_='foreignkey')
    op.create_foreign_key(op.f('component_global_parameters_component_id_fkey'), 'component_global_parameters', 'components', ['component_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_comp_global_param_scalar', table_name='component_global_parameters', postgresql_where=sa.text('"order" IS NULL'))
    op.create_index(op.f('uq_comp_global_param_scalar'), 'component_global_parameters', ['component_id', 'parameter_definition_id'], unique=True, postgresql_where='("order" IS NULL)')
    op.drop_index('uq_comp_global_param_list', table_name='component_global_parameters', postgresql_where=sa.text('"order" IS NOT NULL'))
    op.create_index(op.f('uq_comp_global_param_list'), 'component_global_parameters', ['component_id', 'parameter_definition_id', 'order'], unique=True, postgresql_where='("order" IS NOT NULL)')
    op.drop_column('component_global_parameters', 'component_version_id')
    # ### end Alembic commands ###
