/**
 * Field Expression Types
 *
 * Field expressions allow dynamic referencing of outputs from other components
 * in a workflow graph using the syntax: @{{component_id.port_name::key}}
 */

// ============================================================================
// Backend API Types
// ============================================================================

/**
 * Field expression update payload (sent to backend)
 */
export interface FieldExpressionUpdate {
  field_name: string // The target parameter field name
  expression_text: string // Raw expression like "@{{comp.port::key}}"
}

/**
 * Field expression read response (from backend)
 */
export interface FieldExpressionRead {
  field_name: string
  expression_json: ASTNode // The parsed AST
  expression_text?: string // Original text (optional)
}

/**
 * Auto-generated field expression returned by the graph update endpoint.
 * Identifies the target component instance and carries both parsed AST and raw text.
 */
export interface AutoGeneratedFieldExpression {
  component_instance_id: string
  field_name: string
  expression_json: ASTNode
  expression_text: string
}

// ============================================================================
// AST (Abstract Syntax Tree) Types
// ============================================================================

/**
 * Base AST node
 */
export type ASTNode = LiteralNode | RefNode | ConcatNode

/**
 * Literal text node
 */
export interface LiteralNode {
  type: 'literal'
  value: string
}

/**
 * Variable reference node (simple named variable)
 */
export interface VarNode {
  type: 'var'
  name: string
}

/**
 * Reference node (with optional key extraction)
 */
export interface RefNode {
  type: 'ref'
  instance: string // Component instance UUID
  port: string // Output port name
  key?: string // Optional dict key for extraction
}

/**
 * Concatenation node (multiple parts)
 */
export interface ConcatNode {
  type: 'concat'
  parts: ASTNode[]
}

/**
 * JsonBuildNode structure for complex field expressions
 * Used to separate template structure from field expression references
 */
export interface JsonBuildNode {
  type: 'json_build'
  template: any // The template structure with placeholders
  refs: Record<string, RefNode | VarNode> // Mapping of placeholder names to ref/var nodes
}

// ============================================================================
// Backend Autocomplete Types
// ============================================================================

/**
 * Backend autocomplete response item
 * Used for the new field expression autocomplete endpoint
 */
export interface FieldExpressionAutocompleteSuggestion {
  id: string
  label: string
  insert_text: string // snake_case from backend
  kind: 'module' | 'property' | 'variable'
  description?: string | null
  variable_type?: string | null
  has_default?: boolean | null
}

// ============================================================================
// Autocomplete & Suggestion Types
// ============================================================================

/**
 * Available component for autocomplete
 */
export interface ComponentSuggestion {
  id: string
  name: string // Display name
  ref: string // Label/reference name
  type: 'component' | 'worker'
}

/**
 * Available output port for autocomplete
 */
export interface PortSuggestion {
  name: string // Port name
  type: string // Port data type
  description?: string
  isDict: boolean // Whether this port outputs a dict
  availableKeys?: string[] // If isDict, available keys from schema
}

/**
 * Complete suggestion with component + port info
 */
export interface ExpressionSuggestion {
  component: ComponentSuggestion
  port: PortSuggestion
  key?: string // Optional dict key
  displayText: string // Human-readable display
  insertText: string // Actual expression to insert
}

/**
 * Autocomplete trigger context
 */
export interface AutocompleteContext {
  trigger: '@' | '@{{' | '::'
  query: string
  cursorPosition: number
}

// ============================================================================
// Validation Types
// ============================================================================

/**
 * Expression validation result
 */
export interface ValidationResult {
  isValid: boolean
  errors: ValidationError[]
  warnings: ValidationWarning[]
}

export interface ValidationError {
  message: string
  position?: number
  componentId?: string
  portName?: string
}

export interface ValidationWarning {
  message: string
  suggestion?: string
}

// ============================================================================
// Highlight/Display Types
// ============================================================================

/**
 * Highlighted expression part for rendering
 */
export interface HighlightedPart {
  type: 'text' | 'expression' | 'invalid'
  content: string
  componentId?: string
  portName?: string
  keyName?: string
  tooltip?: string
}

/**
 * Expression parse result for UI
 */
export interface ParsedExpression {
  raw: string
  parts: HighlightedPart[]
  isValid: boolean
  references: ExpressionReference[]
}

/**
 * A reference extracted from an expression
 */
export interface ExpressionReference {
  componentId: string
  componentName?: string
  portName: string
  keyName?: string
  position: number
}

// ============================================================================
// Graph Node Types (for field expressions)
// ============================================================================

/**
 * Graph node data structure used in field expressions
 */
export interface GraphNodeData {
  id: string
  ref?: string
  name?: string
  type?: string
  component_version_id?: string
  outputs?: PortDefinition[]
  [key: string]: unknown
}

/**
 * Port definition from component
 */
export interface PortDefinition {
  name: string
  port_type: 'INPUT' | 'OUTPUT'
  type?: string
  description?: string
  schema?: Record<string, unknown>
}

/**
 * Component definition structure
 */
export interface ComponentDefinition {
  id?: string
  component_version_id?: string
  port_definitions?: PortDefinition[]
  outputs?: PortDefinition[]
  [key: string]: unknown
}

/**
 * Graph edge structure
 */
export interface GraphEdge {
  id: string
  source: string
  target: string
  origin?: string
  destination?: string
  sourceHandle?: string
  targetHandle?: string
}

// ============================================================================
// Mention Types (for TipTap integration)
// ============================================================================

/**
 * Mention item for autocomplete dropdown
 */
export interface MentionItem {
  id: string // The expression text (e.g., "@{{uuid.port}}")
  label: string // Human-readable label
  insertText: string // Same as id, kept for compatibility
}

/**
 * Props passed to mention list renderer
 */
export interface MentionListProps {
  items: MentionItem[]
  command: (item: { id: string; label: string }) => void
  clientRect?: (() => DOMRect | null) | null
}

/**
 * TipTap content node types
 */
export interface TipTapTextNode {
  type: 'text'
  text: string
}

/**
 * TipTap Mention node with field expression data
 * Note: `id` stores the full expression text (e.g., "@{{uuid.port}}") because:
 * - TipTap's Mention extension requires an `id` attribute for node identity
 * - `renderText` uses `id` to serialize mentions back to expression format for backend
 * - `label` stores the human-readable form for display (e.g., "componentRef.portName")
 */
export interface TipTapMentionNode {
  type: 'mention'
  attrs: {
    /** Full expression text for serialization (e.g., "@{{uuid.port}}") */
    id: string

    /** Human-readable label for display (e.g., "componentRef.portName") */
    label: string
  }
}

export interface TipTapParagraphNode {
  type: 'paragraph'
  content?: Array<TipTapTextNode | TipTapMentionNode>
}

export interface TipTapDocNode {
  type: 'doc'
  content: TipTapParagraphNode[]
}
