server:
  http_listen_port: 3200  # Query API port - Grafana connects here

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317  # OTLP gRPC receiver (not used currently)
        http:
          endpoint: 0.0.0.0:4318  # OTLP HTTP receiver - FastAPI traces sent here

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces  # Local storage for trace data
    wal:
      path: /tmp/tempo/wal     # Write-ahead log for durability 