server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          http_listen_port: 4318

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

ingester:
  lifecycler:
    ring:
      replication_factor: 1
      kvstore:
        store: inmemory 