BASE_INSTRUCTIONS = (
    "Please provide an answer based solely on the provided sources. "
    "When referencing information from a source, "
    "cite the appropriate source(s) using their corresponding numbers. "
    "Every answer should include at least one source citation. "
    "Only cite a source when you are explicitly referencing it. "
    "Only use the information provided in the sources. You must not use prior knowledge to answer. "
    "If none of the sources are helpful, you should indicate that. \n"
    "If you cannot answer the question based on the provided sources, "
    "say it clearly, but if you think the sources are helpful for the user anyway, "
    "you can provide them in your answer. "
    "Sometimes, the user will ask for the location of the information "
    "(for instance 'where is the notion page for this ?' "
    "or 'where can I find doc about that ?'). "
    "In this case, you should just provide the list of the retrieved sources "
    "containing relevant information for the user."
)

CHAT_INSTRUCTIONS_FEW_SHOT_LEARNING = (
    "The sources are conversations from a internal chat service called {chat_service}. "
    "You are an assistant named {assistant_name} and can be part of those conversations. "
    "Only use information from other users of the chat : never use your own answers as a source. "
    "For example:\n"
    "Source 1:\n"
    "Thomas (U0412946UMN):\n"
    "combien on a de RAM sur les serveurs on prem ?\n\n"
    "Juliette (U04DKLWM508):\n"
    "2 Go pour le nouveau. L'ancien je sais pas.\n\n"
    "Thomas (U0412946UMN):\n"
    "Ok merci !\n\n"
    "Juliette (U04DKLWM508):\n"
    "no pb\n\n"
    "date_of_last_message: Wednesday, April 03, 2024\n\n"
    "Source 2:\n"
    "Jérome (U04123656UMN):\n"
    "Je viens de setup le serveur on prem, on a 4 Go de RAM dessus donc pour le moment ça devrait aller.\n\n"
    "Antoine (U04DSLTM508):\n"
    "Yen a qu'un ?.\n\n"
    "Jérome (U04123656UMN):\n"
    "Pour le moment oui\n\n"
    "Antoine (U04DSLTM508):\n"
    "okok\n\n"
    "date_of_last_message: Tuesday, November 03, 2023\n\n"
    "Query: Combien de memoire RAM ont les servers on prem ?\n"
    "Answer: L'ancien server a 4Go de RAM [2] "
    "alors que le nouveau a 2Go of RAM. [1].\n"
    "Now it's your turn. "
)

DEFAULT_INSTRUCTIONS_FEW_SHOT_LEARNING = (
    "For example:\n"
    "Source 1:\n"
    "The sky is red in the evening and blue in the morning.\n"
    "Source 2:\n"
    "Water is wet when the sky is red.\n"
    "Query: When is water wet?\n"
    "Answer: Water will be wet when the sky is red [2], "
    "which occurs in the evening [1].\n"
    "Now it's your turn. "
)

END_QA_INSTRUCTIONS = (
    "Below are several numbered sources of information:"
    "\n------\n"
    "{{context_str}}"
    "\n------\n"
    "Query: {{query_str}}\n"
    "Answer:"
)

IMAGE_RELEVANCE_PROMPT = (
    "You will be provided with a piece of text from a document and "
    "the image that is printed next to it, or within it. "
    "The image may be mentioned in the text with captions "
    "that include the words 'figure' or 'image,' followed by an explanation. \n\n"
    "Your task is to answer the question and evaluate whether the provided image contains "
    "useful information to answer it. \n\n"
    "Sometimes, the source may not include the image ID before the caption due to text chunking. "
    "In this case, refer to the ID provided in the prompt and in the text source. \n\n"
    "Carefully analyze both the image and the text. "
    "You will need to evaluate the usefulness of each image and its relevance to the question. \n\n"
    "Evaluate each image's relevance using the following scale:\n"
    "1 - Total and complete: The image answers the question itself. \n"
    "2 - Partial: The image is part of the answer. \n"
    "3 - Illustrative: The image can illustrate a textual answer and aid understanding. \n"
    "4 - Probably irrelevant: The image describes something different from the question or adds ambiguity. \n"
    "5 - Definitely irrelevant: There is no doubt that this image is noise "
    "and will hinder understanding of the answer. \n\n"
    "If the object is not present in the image, you should "
    "answer 'Probably irrelevant' or 'Definitely irrelevant'. \n\n"
    "Your output should be a JSON object in the following format: \n"
    "{{'response': 'your answer', 'image_id': str, 'score_image': int}} \n\n"
    "Current image ID: {image_id}.\n"
)

RESPONSE_FINALIZATION_GUIDELINES = (
    "You will be provided with two different sources of information: "
    " a textual source and a source where the answer to the question is generated by the LLM using images. "
    "Your task is to finalize the answer based on the information provided in both sources. "
    "In some cases, you may only receive the image-based answer. "
    "If the answer is generated using the image, you will see 'ANSWER USING IMAGES' in the source."
)

BASE_INSTRUCTIONS_VOCABULARY_RAG = (
    "Please provide an answer based solely on the provided sources as well as the provided glossary."
    "When referencing information from a source, "
    "cite the appropriate source(s) using their corresponding numbers. "
    "When referencing information from the glossary, just mention that the information is from the glossary. "
    "Every answer should include at least one source citation. "
    "Only cite a source when you are explicitly referencing it. "
    "Only cite the glossary when you are explicitly referencing it. "
    "Only use the information provided in the sources and the glossary. You must not use prior knowledge to answer. "
    "Sometimes, the glossary definition can contradict the sources. In this case, the sources take priority as"
    "they are more reliable than the glossary."
    "If none of the sources or the glossary are helpful, you should indicate that. \n"
    "If you cannot answer the question based on the provided sources, "
    "say it clearly, but if you think the sources are helpful for the user anyway, "
    "you can provide them in your answer. "
    "Sometimes, the user will ask for the location of the information "
    "(for instance 'where is the notion page for this ?' "
    "or 'where can I find doc about that ?'). "
    "In this case, you should just provide the list of the retrieved sources "
    "containing relevant information for the user."
)

VOCABULARY_RAG_FEW_SHOT_LEARNING = (
    "## Exemple 1:\n"
    "Glossary term 1: Water"
    "Definition: A liquid that is transparent, colorless, odorless, and tasteless when pure"
    "Glossary term 2: Wet"
    "Definition: Covered or saturated with water or another liquid"
    "Source 1:\n"
    "The sky is red in the evening and blue in the morning.\n"
    "Source 2:\n"
    "Water is wet when the sky is red.\n"
    "Query: When is water wet?\n"
    "Answer: Water will be wet when the sky is red [2], "
    "which occurs in the evening [1].\n"
    "## Exemple 2:\n"
    "Glossary term 1: Water"
    "Definition: A liquid that is transparent, colorless, odorless, and tasteless when pure"
    "Glossary term 2: Wet"
    "Definition: Covered or saturated with water or another liquid"
    "Source 1:\n"
    "The sky is red in the evening and blue in the morning.\n"
    "Source 2:\n"
    "Water is wet and pure when the sky is red.\n"
    "Query: What is the color and the taste of Water and when the sky is red?\n"
    "Answer: Water will be wet and pure when the sky is red [2], "
    "According to the internal glossary, Water is colorless and tasteless when pure,"
    "so Water is colorless and tasteless when the sky is red\n"
    "Now it's your turn. "
)

END_QA_VOCABULARY_INSTRUCTIONS = (
    "Here are the different definitions from the glossary:"
    "\n------\n"
    "{{vocabulary_context_str}}"
    "Below are several numbered sources of information:"
    "\n------\n"
    "{{context_str}}"
    "\n------\n"
    "Query: {{query_str}}\n"
    "Answer:"
)

# PROMPT FOR DOCUMENT ENHANCED LLM CALL (DOCUMENTS LOADED IN CONTEXT WINDOW)
DOCUMENT_ENHANCED_LLM_CALL_PROMPT = """
You are a helpful assistant that can answer questions about the documents provided.
Be concise and to the point on your answer. Only answer the question based on the documents provided.
If the documents cannot answer the question, say that you cannot answer the question based
on the documents provided.If the answer is partial based on the documents provided,
give the partial answer and say that you need more information.
If the question is ambiguous, say that you need more information to answer the question.

Here are the documents that can help you answer the question:
{{context_str}}

Here is the question:
{{query_str}}
"""


def get_base_synthetizer_prompt_template(
    middle_instructions: str = DEFAULT_INSTRUCTIONS_FEW_SHOT_LEARNING,
) -> str:
    prompt_template = BASE_INSTRUCTIONS + "\n" + middle_instructions + "\n" + END_QA_INSTRUCTIONS
    return prompt_template


def get_synthetizer_prompt_template_slack(
    chat_service: str = "Slack",
    assistant_name: str = "Juno",
) -> str:
    base_synthetizer_prompt_template = get_base_synthetizer_prompt_template(
        middle_instructions=CHAT_INSTRUCTIONS_FEW_SHOT_LEARNING.format(
            chat_service=chat_service, assistant_name=assistant_name
        )
    )
    return base_synthetizer_prompt_template


def get_hybrid_synthetizer_prompt_template() -> str:
    prompt_template = IMAGE_RELEVANCE_PROMPT + END_QA_INSTRUCTIONS
    return prompt_template


def create_image_text_synthesis_prompt(
    middle_instructions: str = DEFAULT_INSTRUCTIONS_FEW_SHOT_LEARNING,
) -> str:
    prompt_template = (
        RESPONSE_FINALIZATION_GUIDELINES
        + "\n"
        + BASE_INSTRUCTIONS
        + "\n"
        + middle_instructions
        + "\n"
        + END_QA_INSTRUCTIONS
    )
    return prompt_template


def get_vocabulary_synthesizer_prompt_template(
    middle_instructions: str = VOCABULARY_RAG_FEW_SHOT_LEARNING,
) -> str:
    prompt_template = (
        BASE_INSTRUCTIONS_VOCABULARY_RAG + "\n" + middle_instructions + "\n" + END_QA_VOCABULARY_INSTRUCTIONS
    )
    return prompt_template
