COMPLETION_MODEL_IN_DB = "completion_model"
EMBEDDING_MODEL_IN_DB = "embedding_model"
WEB_SERVICE_IN_DB = "web_service"
TEMPERATURE_IN_DB = "default_temperature"
VERBOSITY_IN_DB = "verbosity"
REASONING_IN_DB = "reasoning"
