apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [ 'service.name', 'span.name' ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_count{$$__tags}[5m])) by ($$__rate_by)' 