apiVersion: 1

datasources:
  # Prometheus datasource for performance metrics
  # Connects to: prometheus service port 9090
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # Tempo datasource for distributed tracing
  # Connects to: tempo service query API port 3200
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      # Links traces to metrics for correlation
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [ 'service.name', 'span.name' ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_count{$$__tags}[5m])) by ($$__rate_by)' 