apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${GRAFANA_PROMETHEUS_HOST}:${GRAFANA_PROMETHEUS_PORT}
    uid: prometheus
    isDefault: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://${GRAFANA_TEMPO_HOST}:${GRAFANA_TEMPO_PORT}
    uid: tempo
    jsonData:
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [ 'service.name', 'span.name' ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_count{$$__tags}[5m])) by ($$__rate_by)'